<?php
require('cceUtil.php');



function v3_cce_format_download_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'v3_cce_format_download'),
  );
}


function v3_cce_format_download_help($path, $arg) {
  global $user;

  switch ($path) {
    case 'assess':
      return '<p>'. t('We can download the file format for uploading marks and attendance details.') .'</p>';
	
	}
  
}  
function v3_cce_format_download_menu() {
	$items['formatfile'] = array(
    'title' => 'CCE - Data Format Download',
    'description' => 'Download Data Format for CoScholastic or Scholastic',
    'page callback' => 'cce_download',
    'page arguments' => array('dload'),
    // 'access arguments' => array('administer users'),
	'type' => MENU_CALLBACK,
'access callback' => 'user_access',
			'access arguments' => array('access content'),	
	);

  $items['formatfile/dload'] = array(
    'title' => 'download',
    'type' => MENU_DEFAULT_LOCAL_TASK,
'access callback' => 'user_access',
			'access arguments' => array('access content'),
    'weight' => -10,
  );
  
  
return $items;
}

function cce_download($callback_arg = '') {
/*
        $output = drupal_get_form('assess_filter_form');
        $output .= drupal_get_form('assess_details');
  return $output;
  */
  
  $op = isset($_POST['op']) ? $_POST['op'] : $callback_arg;

//  drupal_set_message("Operamd - $op ");	
  
  switch ($op) {
    case t('Download Scholastic Format'):
	case t('Download CoScholastic Format'):
	case t('Download Student Attendance Format');
	case t('Download Optional Subjects');	
    case 'download':
      $output = drupal_get_form('download_create');
      break;

	  default:
      $output = drupal_get_form('download_create');
  }
  return $output;
  
}

function download_create() {


// get the list of active Year

		db_set_active('qtxt_db');	
		$result1 = db_query("SELECT account_grade_id, grade_name  FROM {qtxt_sms_account_grades} a where group_id is not null order by grade_name");
		$yearOptions = array( '' => t('Select the Class') );
		while ($row = db_fetch_object($result1)){
		  $yearOptions[$row->account_grade_id ] = $row->grade_name; 
		}
		db_set_active('default');	


		$form['class'] = array(
			'#type' => 'select',
			'#description' => t('Please select the Class'),
			'#options'=> $yearOptions,
			'#title' => t('Class'),
			'#disabled' => FALSE
		);
		
		
	 $form['buttons']['submit'] = array(                                                          
		'#type' => 'submit',
		'#value' => t('Download Scholastic Format'),  
                '#prefix' => '<br/><br/><br/><br/><br/>',                                               
	  );

	 $form['buttons']['submit1'] = array(                                                          
		'#type' => 'submit',
		'#value' => t('Download CoScholastic Format'),                                                 
	  );	  

	 $form['buttons']['submit2'] = array(                                                          
		'#type' => 'submit',
		'#value' => t('Download Student Attendance Format'),                                                 
	  );	  

	 $form['buttons']['submit3'] = array(                                                          
		'#type' => 'submit',
		'#value' => t('Download Optional Subjects'),                                                 
	  );	  
    return $form;
$form['buttons']['submit']['#attributes']['class']  = $form['buttons']['submit']['#attributes']['class'] . ' qbsubmit';

}
function download_create_validate($form, &$form_state) {
$accountGradeId = $form_state['values']['class'];

if ( $accountGradeId == "") {
		form_set_error('', t('Pease select the class'));
	}	
}

function download_create_submit($form, &$form_state) {
		  
   $op = $form_state['values']['op'];
  
   if ( $op == "Download CoScholastic Format" ) {
			$file_path = "CoScholasticFileFormat.csv";   
			$accountGradeId = $form_state['values']['class'];

			db_set_active('qtxt_db');	
			$result1 = db_query("SELECT concat(standard,section) grade_name  FROM {qtxt_sms_account_grades} a where account_grade_id = $accountGradeId order by grade_name");
			$rowg1 = db_fetch_object($result1);
			$grade = $rowg1->grade_name;
			
			$a = new Qtxt_Util();
			$a->cceGetCoSchol_Simplified($accountGradeId);
			
			//    drupal_set_header('Pragma: public');
			//   drupal_set_header('Cache-Control: cache, must-revalidate');
			//    drupal_set_header('Accept-Ranges: bytes');
			//    drupal_set_header('Content-Range: bytes ' . $seek_start . '-' . $seek_end . '/' . $size);
			//    drupal_set_header('Content-Type: ' . $mimetype);


			$filename = "CoScholasticFileFormat.csv";			
						drupal_set_header("Content-type: application/x-unknown; utf-8");
						drupal_set_header('Content-Disposition: attachment; filename="' . $grade. date('_d-m-Y_') . "coscholastic.csv" . '"');
			 drupal_set_header('ETag: ' . md5($file_path));

			  // Open the file and seek to starting byte
				$fp = fopen($file_path, 'rb');
			//    fseek($fp, $seek_start);

				// Start buffered download
				while (!feof($fp)) {
				  // Reset time limit for large files
				  set_time_limit(0);
				  print(fread($fp, 1024 * 8));
				  flush();
				  ob_flush();
				}

				// Finished serving the file, close the stream and log the download to the user table
				fclose($fp);
				exit();
			
			
   } else if  ( $op == "Download Scholastic Format" ) {
			$file_path = "ScholasticFileFormat.csv";   
			$accountGradeId = $form_state['values']['class'];

			db_set_active('qtxt_db');	
			$result1 = db_query("SELECT concat(standard,section) grade_name  FROM {qtxt_sms_account_grades} a where account_grade_id = $accountGradeId");
			$rowg1 = db_fetch_object($result1);
			$grade = $rowg1->grade_name;
			
			$a = new Qtxt_Util();
			$a->cceGetSchol_Simplified($accountGradeId);
			
			//    drupal_set_header('Pragma: public');
			//   drupal_set_header('Cache-Control: cache, must-revalidate');
			//    drupal_set_header('Accept-Ranges: bytes');
			//    drupal_set_header('Content-Range: bytes ' . $seek_start . '-' . $seek_end . '/' . $size);
			//    drupal_set_header('Content-Type: ' . $mimetype);


			$filename = "ScholasticFileFormat.csv";			
						drupal_set_header("Content-type: application/x-unknown; utf-8");
						drupal_set_header('Content-Disposition: attachment; filename="' . $grade. date('_d-m-Y_') . "scholastic.csv" . '"');
			 drupal_set_header('ETag: ' . md5($file_path));

			  // Open the file and seek to starting byte
				$fp = fopen($file_path, 'rb');
			//    fseek($fp, $seek_start);

				// Start buffered download
				while (!feof($fp)) {
				  // Reset time limit for large files
				  set_time_limit(0);
				  print(fread($fp, 1024 * 8));
				  flush();
				  ob_flush();
				}

				// Finished serving the file, close the stream and log the download to the user table
				fclose($fp);
				exit();   
   } else if ( $op == "Download Student Attendance Format" ) {
			$file_path = "StudentAttendanceFileFormat.csv";   
			$accountGradeId = $form_state['values']['class'];

			db_set_active('qtxt_db');	
			$result1 = db_query("SELECT concat(standard,section) grade_name  FROM {qtxt_sms_account_grades} a where account_grade_id = $accountGradeId");
			$rowg1 = db_fetch_object($result1);
			$grade = $rowg1->grade_name;
			
			$a = new Qtxt_Util();
			$a->cceGetAttendance_Simplified($accountGradeId);
			
			//    drupal_set_header('Pragma: public');
			//   drupal_set_header('Cache-Control: cache, must-revalidate');
			//    drupal_set_header('Accept-Ranges: bytes');
			//    drupal_set_header('Content-Range: bytes ' . $seek_start . '-' . $seek_end . '/' . $size);
			//    drupal_set_header('Content-Type: ' . $mimetype);


			$filename = "ScholasticFileFormat.csv";			
						drupal_set_header("Content-type: application/x-unknown; utf-8");
						drupal_set_header('Content-Disposition: attachment; filename="' . $grade. date('_d-m-Y_') . "attendance.csv" . '"');
			 drupal_set_header('ETag: ' . md5($file_path));

			  // Open the file and seek to starting byte
				$fp = fopen($file_path, 'rb');
			//    fseek($fp, $seek_start);

				// Start buffered download
				while (!feof($fp)) {
				  // Reset time limit for large files
				  set_time_limit(0);
				  print(fread($fp, 1024 * 8));
				  flush();
				  ob_flush();
				}

				// Finished serving the file, close the stream and log the download to the user table
				fclose($fp);
				exit();   
   
   } else if ( $op == "Download Optional Subjects" ) {
			$file_path = "OptionalSubjectsFileFormat.csv";   
			$accountGradeId = $form_state['values']['class'];
// drupal_set_message("I am here  - $accountGradeId ");	
//			return;
			
			db_set_active('qtxt_db');	
			$result1 = db_query("SELECT concat(standard,section) grade_name  FROM {qtxt_sms_account_grades} a where account_grade_id = $accountGradeId");
			$rowg1 = db_fetch_object($result1);
			$grade = $rowg1->grade_name;
			db_set_active('default');	
			
			$a = new Qtxt_Util();
			$a->cceUploadOptionalSubjects($accountGradeId);

			// $filename = "ScholasticFileFormat.csv";			
						drupal_set_header("Content-type: application/x-unknown; utf-8");
						drupal_set_header('Content-Disposition: attachment; filename="' . $grade. date('_d-m-Y_') . "optional_subjects.csv" . '"');
			 drupal_set_header('ETag: ' . md5($file_path));

			  // Open the file and seek to starting byte
				$fp = fopen($file_path, 'rb');
			//    fseek($fp, $seek_start);

				// Start buffered download
				while (!feof($fp)) {
				  // Reset time limit for large files
				  set_time_limit(0);
				  print(fread($fp, 1024 * 8));
				  flush();
				  ob_flush();
				}

				// Finished serving the file, close the stream and log the download to the user table
				fclose($fp);
				exit();   
   
   }
   

}





