<?php
/**
 * Implementation of hook_views_api().
 *
 */
// require ( "../quadroquest/SMSLibrary.php");
require ( "cceClass.php");

function v3_cce_main_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'v3_cce_main'),
  );
}



function v3_cce_main_menu() {
	$items['cceupload'] = array(
			'title' => t('CCE File Upload  - Welcome Screen'),
			'page callback' => 'v3_cce_main_submit_form_wrap',
			'type' => MENU_CALLBACK,
			'access callback' => 'user_access',
			'access arguments' => array('access content'),
	);
	$items['cceupload/next'] = array(
			'title' => t('Online Messages to Parents  - Next Screen'),
			'page callback' => 'v3_cce_main_submit_next_form_wrap',
			'type' => MENU_CALLBACK,
			'access callback' => 'user_access',
			'access arguments' => array('access content'),
	);
	
return $items;
}

function v3_cce_main_submit_form_wrap() {
			$output = drupal_get_form('v3_cce_main_submit_form');
			return $output ;
}

function v3_cce_main_submit_next_form_wrap() {
			$output = drupal_get_form('v3_cce_main_submit_next_form');
			return $output ;
}



 
function v3_cce_main_submit_form( $form_state) {

global $user;
//$profile =  profile_load_profile($user);
//$myMobileNumber =  $user->profile_mobile;  

//$defusermobile = $myMobileNumber;
$defadminuserid = "";
$defadminpwd = "";

	  

	  db_set_active('qtxt_db');	

	  
	  $resultg1 = db_query("select account_id, account_name from {qtxt_sms_account} WHERE party_id = 5 ");
				  $igradeOptions = array();
				  while ($rowg1 = db_fetch_object($resultg1)) {
				  	$igradeOptions[$rowg1->account_id ] =  $rowg1->account_name; //This is the only line that changed from the code above.
				  	}
	db_set_active('default');
				  $form['institution'] = array('#type' => 'select',
				  				  		'#options' => $igradeOptions,
				  				  		'#title' => t('Institution'),
				  				  		'#description' => t('Please select the Institution '),
				  				  		'#disabled' => FALSE,
				  );
				  
	  db_set_active('qtxt_db');	

	  
	  $resultg1 = db_query("select concat_ws ( '  -  ' ,cg.group_name ,  ct.term_name, cat.assessment_name, cat.assessment_type_code) assessment_desc, assessment_id from {cce_assesment_types} cat, {cce_groups} cg, {cce_term} ct where cg.group_id = cat.group_id and ct.term_id = cat.term_id order by group_name, term_name, assessment_name ");
				  $igradeOptions = array();
				  while ($rowg1 = db_fetch_object($resultg1)) {
				  	$igradeOptions[$rowg1->assessment_id ] =  $rowg1->assessment_desc; 
				  	}
	db_set_active('default');
				  $form['assessment'] = array('#type' => 'select',
				  				  		'#options' => $igradeOptions,
				  				  		'#title' => t('Assessment Type'),
				  				  		'#description' => t('Please select the Assessment Type '),
				  				  		'#disabled' => FALSE,
				  );


				  db_set_active('qtxt_db');	

	  $form['#attributes']['enctype'] = "multipart/form-data";
	  
	  $resultg1 = db_query("select template_id, template_name from {qtxt_sms_template_master} where tag = 'cce'");
				  $igradeOptions2 = array();
				  while ($rowg1 = db_fetch_object($resultg1)) {
				  	$igradeOptions2[$rowg1->template_id ] =  $rowg1->template_name; //This is the only line that changed from the code above.
				  	}
				db_set_active('default');				  
				  
				  $form['interfaceType'] = array('#type' => 'select',
				  				  		'#title' => t('Interface Type'),
										'#options' =>  $igradeOptions2,
				  				  		'#description' => t('Please select the Template'),
				  				  		'#disabled' => FALSE,
				  );
				  
				  $form['tcsv'] = array('#type' => 'file',
				  				  		'#title' => t('Upload File'),
				  				  		'#description' => t('Pick a file to upload'),
				  );
				  

			  $form['submit'] = array(
				'#type' => 'submit',
				'#value' => t('Confirm'),
			  );
			return $form;
 
}



function v3_cce_main_submit_form_submit($form, &$form_state) {
	global $user;
//	$profile =  profile_load_profile($user);
//	$myMobileNumber =  $user->profile_mobile; 
//	$uid = $user->uid;
//	$_SESSION['t_student'] = $form_state['values']['institution'];
//	$_SESSION['t_student_grade'] = $form_state['values']['adminOuter']['grade'];

	$dir = file_directory_path();

		if(isset($_FILES) && !empty($_FILES) && $_FILES['files']['size']['tcsv'] != 0){
		
			#this structure is kind of wacky
			$name = $_FILES['files']['name']['tcsv'];
			$size = $_FILES['files']['size']['tcsv'];
			$type = $_FILES['files']['type']['tcsv'];

			#this is the actual place where we store the file
			$file = file_save_upload('tcsv', array() , $dir);

		} 	
		
	$_SESSION['ccefilename'] = $name;
	$_SESSION['ccedir'] = $dir;
	$_SESSION['cceaccount'] = $form_state['values']['institution'];
	$_SESSION['t_interface_type'] = $form_state['values']['interfaceType'];	
	$_SESSION['cceassessment'] = $form_state['values']['assessment'];
	
	$form_state['redirect'] = 'cceupload/next';
  return;

}

function v3_cce_main_submit_next_form ($form_state) {

	$name = &$_SESSION['ccefilename'];
	$dir = &$_SESSION['ccedir'];
	$acc = &$_SESSION['cceaccount'];
	$intType = &$_SESSION['t_interface_type'];	
	$assId = &$_SESSION['cceassessment'];	
	$filename = $dir . '/' .$name ;
	drupal_set_message( "$name" ) ;
	drupal_set_message( "$dir" ) ;
	drupal_set_message( "$acc" ) ;	
	drupal_set_message( "$intType" ) ;
	drupal_set_message( "$assId" ) ;
	
	$sms= new Qtxt_CCE_Common;
	
	
//	$rs5 = $sms->cceLoad1A( $filename, $acc, $intType );
	$rs5 = $sms->cceMainLoad( $filename, $acc, $intType, $assId );	
	
	
	if ( $intType ==101 ) {
	$form[$rowval]['tabstart'] = array( '#value' => "", '#prefix'=>'<table  class="views-view-grid" >  <tbody> ', );
	$i = 1 ;
	$j = 1;
	//SELECT Student_Id,Student_Name,class, section, year,batch_id,row_id,process_status,process_flag
	
				while($row3 = mysql_fetch_assoc($rs5)) {
					$rowval = "row" . $i;
						$j = 1;
					$form[$rowval]['template'] = array( '#value' => $row3["Student_Id"], '#prefix'=>'<tr class="row-".$i  ><td class="col-1" >', '#suffix' => '</td>',);
					$j =  $j + 1;
					$form[$rowval]['templaten'] = array( '#value' => $row3["Student_Name"], '#prefix'=>'<td class="col-2" >', '#suffix' => '</td>',);
					$j =  $j + 1;
					$form[$rowval]['active'] = array( '#value' => $row3["process_flag"], '#prefix'=>'<td class="col-3" >', '#suffix' => '</td>',);
					$j =  $j + 1;
					$form[$rowval]['tag'] = array( '#value' => $row3["process_status"], '#prefix'=>'<td  class="col-4">', '#suffix' => '</td></tr>',);
					$i =  $i + 1;
				}

		$form[$rowval]['tabend'] = array( '#value' => "", '#suffix' => '</table>',);	
	}
	elseif ( $intType ==102 )  {
			$form[$rowval]['tabstart'] = array( '#value' => "", '#prefix'=>'<table  class="views-view-grid" >  <tbody> ', );
			$i = 1 ;
			$j = 1;
						while($row3 = mysql_fetch_assoc($rs5)) {
							$rowval = "row" . $i;
								$j = 1;
							$form[$rowval]['template'] = array( '#value' => $row3["Student_Id"], '#prefix'=>'<tr class="row-".$i  ><td class="col-1" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['templaten'] = array( '#value' => $row3["Student_Name"], '#prefix'=>'<td class="col-2" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['active'] = array( '#value' => $row3["process_flag"], '#prefix'=>'<td class="col-3" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['tag'] = array( '#value' => $row3["process_status"], '#prefix'=>'<td  class="col-4">', '#suffix' => '</td></tr>',);
							$i =  $i + 1;
						}

				$form[$rowval]['tabend'] = array( '#value' => "", '#suffix' => '</table>',);
	}
	elseif ( $intType ==103 )  {
			$form[$rowval]['tabstart'] = array( '#value' => "", '#prefix'=>'<table  class="views-view-grid" >  <tbody> ', );
			$i = 1 ;
			$j = 1;
						while($row3 = mysql_fetch_assoc($rs5)) {
							$rowval = "row" . $i;
								$j = 1;
							$form[$rowval]['template'] = array( '#value' => $row3["Student_Id"], '#prefix'=>'<tr class="row-".$i  ><td class="col-1" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['templaten'] = array( '#value' => $row3["Student_Name"], '#prefix'=>'<td class="col-2" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['active'] = array( '#value' => $row3["process_flag"], '#prefix'=>'<td class="col-3" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['tag'] = array( '#value' => $row3["process_status"], '#prefix'=>'<td  class="col-4">', '#suffix' => '</td></tr>',);
							$i =  $i + 1;
						}

				$form[$rowval]['tabend'] = array( '#value' => "", '#suffix' => '</table>',);
	}
	elseif ( $intType ==104 )  {
			$form[$rowval]['tabstart'] = array( '#value' => "", '#prefix'=>'<table  class="views-view-grid" >  <tbody> ', );
			$i = 1 ;
			$j = 1;
						while($row3 = mysql_fetch_assoc($rs5)) {
							$rowval = "row" . $i;
								$j = 1;
							$form[$rowval]['template'] = array( '#value' => $row3["Student_Id"], '#prefix'=>'<tr class="row-".$i  ><td class="col-1" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['templaten'] = array( '#value' => $row3["Student_Name"], '#prefix'=>'<td class="col-2" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['active'] = array( '#value' => $row3["process_flag"], '#prefix'=>'<td class="col-3" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['tag'] = array( '#value' => $row3["process_status"], '#prefix'=>'<td  class="col-4">', '#suffix' => '</td></tr>',);
							$i =  $i + 1;
						}

				$form[$rowval]['tabend'] = array( '#value' => "", '#suffix' => '</table>',);
	}
	elseif ( $intType ==105 )  {
			$form[$rowval]['tabstart'] = array( '#value' => "", '#prefix'=>'<table  class="views-view-grid" >  <tbody> ', );
			$i = 1 ;
			$j = 1;
						while($row3 = mysql_fetch_assoc($rs5)) {
							$rowval = "row" . $i;
								$j = 1;
							$form[$rowval]['template'] = array( '#value' => $row3["Student_Id"], '#prefix'=>'<tr class="row-".$i  ><td class="col-1" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['templaten'] = array( '#value' => $row3["Student_Name"], '#prefix'=>'<td class="col-2" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['active'] = array( '#value' => $row3["process_flag"], '#prefix'=>'<td class="col-3" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['tag'] = array( '#value' => $row3["process_status"], '#prefix'=>'<td  class="col-4">', '#suffix' => '</td></tr>',);
							$i =  $i + 1;
						}

				$form[$rowval]['tabend'] = array( '#value' => "", '#suffix' => '</table>',);
	}
	elseif ( $intType ==106 )  {
			$form[$rowval]['tabstart'] = array( '#value' => "", '#prefix'=>'<table  class="views-view-grid" >  <tbody> ', );
			$i = 1 ;
			$j = 1;
						while($row3 = mysql_fetch_assoc($rs5)) {
							$rowval = "row" . $i;
								$j = 1;
							$form[$rowval]['template'] = array( '#value' => $row3["Student_Id"], '#prefix'=>'<tr class="row-".$i  ><td class="col-1" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['templaten'] = array( '#value' => $row3["Student_Name"], '#prefix'=>'<td class="col-2" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['active'] = array( '#value' => $row3["process_flag"], '#prefix'=>'<td class="col-3" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['tag'] = array( '#value' => $row3["process_status"], '#prefix'=>'<td  class="col-4">', '#suffix' => '</td></tr>',);
							$i =  $i + 1;
						}

				$form[$rowval]['tabend'] = array( '#value' => "", '#suffix' => '</table>',);
	}
	else {
			$form[$rowval]['tabstart'] = array( '#value' => "", '#prefix'=>'<table  class="views-view-grid" >  <tbody> ', );
			$i = 1 ;
			$j = 1;
						while($row3 = mysql_fetch_assoc($rs5)) {
							$rowval = "row" . $i;
								$j = 1;
							$form[$rowval]['template'] = array( '#value' => $row3["template_id"], '#prefix'=>'<tr class="row-".$i  ><td class="col-1" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['templaten'] = array( '#value' => $row3["template_name"], '#prefix'=>'<td class="col-2" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['active'] = array( '#value' => $row3["active_flag"], '#prefix'=>'<td class="col-3" >', '#suffix' => '</td>',);
							$j =  $j + 1;
							$form[$rowval]['tag'] = array( '#value' => $row3["tag"], '#prefix'=>'<td  class="col-4">', '#suffix' => '</td></tr>',);
							$i =  $i + 1;
						}

				$form[$rowval]['tabend'] = array( '#value' => "", '#suffix' => '</table>',);
	}
	
	/*
		print "<table border cellpadding=3>";	
			while($row3 = mysql_fetch_assoc($rs5))
			{
				print "<tr>";
				print "<th>Student Identifier</th><td>".$row3["template_id"]."</td>";
				print "<th>Route Number </th><td>".$row3["template_name"]."</td>";
				print "<th>Active Flag </th><td>".$row3["active_flag"]."</td>";
				print "<th>Stop Name </th><td>".$row3["tag"]."</td>";
				print "<th>Batch Id</th><td>".$row3["batch_id"]."</td>";
				print "</tr>";
			}
		print "</table>";	
	*/
	return $form;
	
}



