<?php



/**



 * Implementation of hook_views_api().



 *



 */



// require ( "../quadroquest/svrs/QtxtSVRSLibrary.php");



function v3_pmsg_log_views_api() {



  return array(



    'api' => 2,



    'path' => drupal_get_path('module', 'v3_pmsg_log'),



  );



}



function v3_pmsg_log_menu() {



	$items['pmsg_log'] = array(



			'title' => t('Sent Messages To Staff'),



			'page callback' => 'v3_pmsg_log_cb_form',



			'type' => MENU_CALLBACK,



			'access callback' => 'user_access',



			'access arguments' => array('access content'),







	);



	return $items;



	}



 function v3_pmsg_log_cb_form() {



			 $output = drupal_get_form('v3_pmsg_log_form');



			return $output ;



} 



function v3_pmsg_log_form($form_state) {



global $user;



$profile =  profile_load_profile($user);



$myMobileNumber =  $user->profile_mobile; 



$uid = $user->uid;



$header = array(



    array(),



    array('data' => t('Student Name'), 'field' => 'b.student_name,'),



    array('data' => t('Standard'), 'field' => 'b.grade_name'),



    array('data' => t('DOB'), 'field' => 'b.dob'),



    array('data' => t('Account Student id'), 'field' => 'b.account_student_map_id'),



  );



  db_set_active('qtxt_db');	



 	$sql = "select parent_message_id,message,creation_date,parent_uid,teacher_name from {qtxt_sms_parent_messages_v8} where parent_uid = $uid order by 1 desc  "  ;



     $query_count = "select count(parent_message_id) from {qtxt_sms_parent_messages_v8}  where parent_uid =$uid " ;



	 $sql .= tablesort_sql($header);



   $result = pager_query($sql, 100000, 0, $query_count);



  $account = array();



$i = 1;  



  while ($account = db_fetch_object($result)) {



	$form['access']['account'][$i] = array(



	//	'#type' => 'checkbox',



		'#return_value' => $account->parent_message_id,



		'#default_value' => 0,



		'#tree' => TRUE,



		'#disabled'=>True,







	  );



    $form['access']['dob'][$account->parent_message_id] =  array('#value' => $account->teacher_name);
   $form['access']['studentname'][$account->parent_message_id] = array('#value' => $account->message);
    $form['access']['standard'][$account->parent_message_id] =  array('#value' => $account->creation_date);
	 $form['access']['studentid'][$account->parent_message_id] =  array('#type' => 'hidden','#value' => $account->parent_message_id);



$i = $i + 1;



  }



db_set_active('default');



 //  $form['pager'] = array('#value' => theme('pager', NULL, 10, 0));



  $form['#theme'] = 'v3_pmsg_log_form_theme';   



  $form['totalcount'] = array(



	'#type' => 'hidden', '#default_value' => ($i  -1 )



  );  



  return $form;



}  



  function v3_pmsg_log_theme() {



	return array(



		'v3_pmsg_log_form_theme' => array('arguments'=> array('form' => NULL),),



	);







}



function theme_v3_pmsg_log_form_theme($form)



{



$rows = array();



$i = 1;



foreach(element_children($form['access']['studentid']) as $key) {



	$row = array();



     //  $row[] =  drupal_render($form['access']['account'][$i]);



	 $row[] =  drupal_render($form['access']['dob'][$key]);



	   $row[] =  drupal_render($form['access']['studentname'][$key]);



       $row[] =  drupal_render($form['access']['standard'][$key]);



	   



	   $rows[] = $row; 



	$i = $i +1 ;



}



if(count($rows)){



			 $header = array(  t('Staff Name'), t('Message'),  t('Message Sent On'));



  }



  else{



    $header = array(t(''), t('')); 



    $row = array();



   $row[] = array



    (



     'data' => t('No Messages'),



      'colspan' => 2,



     'style' => 'text-align:center'



    );



    $rows[] = $row;



  }



$output = theme('table', $header, $rows); 



return $output . drupal_render($form); 



}  











































































































