<?php





function ver3_hwork_info1_views_api() {

  return array(

    'api' => 2,

    'path' => drupal_get_path('module', 'ver3_hwork_info1'),

  );

}



function ver3_hwork_info1_menu() {

$items['hwork1'] = array(

			'title' => t('Home work and Assignments'),

			'page callback' => 'v3_teacher_hwork_msg_form1',

			'type' => MENU_CALLBACK,

			'access callback' => 'user_access',

			'access arguments' => array('access content'),

	);

	return $items;

	

	}

	

function v3_teacher_hwork_msg_form1() {

			//unset ( $_SESSION['user_class_filter'] );
			
 
			// $output = drupal_get_form('v3_hwork_filter_form1');

			 $output .= drupal_get_form('v3_hwork_my_form1');
			return $output ;

}

function ver3_hwork_info1_theme() {

	return array(

		'v3_hwork_my_form1_theme' => array('arguments'=> array('form' => NULL),),

	);

}





function v3_hwork_filter_form1($form_state) {

global $user;
$profile =  profile_load_profile($user);
$myMobileNumber =  $user->profile_mobile; 
$uid = $user->uid;
$clVal = &$_SESSION['user_class_filter_value'];

// drupal_set_message(t("Class Filter 1 , $clVal"));	

/*
	if(!empty($_SESSION['user_class_filter_value'])) {

		$clVal = &$_SESSION['user_class_filter_value'];

	} else {

		$clVal = "";

	}
*/
	
// $_SESSION['user_class_filter_value'] = $clVal;


 $i = 0;

  $form['filters'] = array(

    '#type' => 'fieldset',

    '#title' => t('Filter Grade Here'),

   // '#theme' => 'user_filters',

  );



db_set_active('qtxt_db');	
$result = db_query("select distinct(a.account_grade_id),a.grade_name from {qtxt_sms_mobile_students_v} a where a.drupal_uid = $uid ");
$options = array('' => t('Select..'));
while ($row = db_fetch_object($result)) {
  $options[$row->account_grade_id ] =  $row->grade_name; 
}
db_set_active('default');	
  

    $form['filters'][ 'class'] = array(
'#title' => t('Grade'),
      
'#type' => 'select',
      '#options' => $options,
    );
  


$form['filters']['class']['#default_value']	= $clVal;
//$form['filters']['class']['#value']	= $clVal;


 $form['filters']['buttons']['submit'] = array(

    '#type' => 'submit',

    '#value' => t('Filter'),

  );

return $form;



}

function v3_hwork_filter_form1_submit($form, &$form_state) {

global $user;
$profile =  profile_load_profile($user);
$myMobileNumber =  $user->profile_mobile; 
$uid = $user->uid;



  $op = $form_state['values']['op'];
  
  $val1 = $form_state['values']['filters'][ 'class'];
  $val2 = $form_state['values'][ 'class'];
 // $val3 = $form_state['values']['filters']['status'][ 'class'];
  
  //drupal_set_message(t("Value 1 $val1 "));	  
  //drupal_set_message(t("Value 2 $val2 "));	  
 // drupal_set_message(t("Value 3 $val3 "));	  

  switch ($op) {

    case t('Filter'): 

      if (isset($form_state['values'][ 'class'])) {

			$filter = $form_state['values'][ 'class'];
			// drupal_set_message(t("After Submit, Value Selected $filter "));	  

			$_SESSION['user_class_filter_value'] = $filter;

      } else  {

			// drupal_set_message(t("In the Filter, Class not selected"));	  
	  }

	  break;

    case t('Undo'):

//      array_pop($_SESSION['user_overview_filter']);

      break;

    case t('Reset'):

//      $_SESSION['user_overview_filter'] = array();

      break;

    case t('Delete'):

      return;

  }

 // $clVal = &$_SESSION['user_5_filter_value'] ;

         // $c2Val = &$_SESSION['user_section_filter_value'] ;

$form_state['redirect'] = 'hwork';
  return;

}



function v3_hwork_my_form1($form_state) {

global $user;

$profile =  profile_load_profile($user);

$myMobileNumber =  $user->profile_mobile; 

$uid = $user->uid;



  $header = array(

    array(),

    // array('data' => t('Teacher Name'), 'field' => 'b.teacher_name'),
      
       array('data' => t('Grade'), 'field' => 'b.grade_name'),

//	array('data' => t('Student Name'), 'field' => 'b.student_name'),

    array('data' => t('Message'), 'field' => 'b.message'),
	
	array('data' => t('Due Date'), 'field' => 'b.str_due_date'),

  //  array('data' => t('File Name'), 'field' => 'b.file_name'),

   // array('data' => t('Msg For'), 'field' => 'b.msg_type'),

	//array('data' => t('Created On'), 'field' => 'b.msg_creation_date'),

	



  );



$clVal = &$_SESSION['user_class_filter_value'] ;

//$c2Val = &$_SESSION['user_section_filter_value'] ;

// drupal_set_message(t("log 1 Class Filter 1 , $clVal"));	

  

$filterClass = "";


	

	 if  ( ( ! isset($clVal) )|| ( $clVal == "" ) ) {
	//	if  ( $c1Val == "" ) {
		$accountArray = "";
		// drupal_set_message(t("log 2 c1Val Not Set "));	
		db_set_active('qtxt_db');	

		$result = db_query("select a.account_grade_id from {qtxt_sms_mobile_students_v} a  where a.drupal_uid = $uid ");

		$accountGradeId = array();

		while ($row = db_fetch_object($result)) {

		  $accountGradeId[] =  $row->account_grade_id; 
		  // This is the only line that changed from the code above.
		}
		db_set_active('default');
		
		if (  count( $accountGradeId ) > 0 ) {
			$accountArray = join( ",", $accountGradeId );
		}
		$filterClass = " and b.account_grade_id in (" . $accountArray . " ) ORDER BY b.str_due_date ASC";
	} else {
		$filterClass = " and b.account_grade_id = '$clVal' ORDER BY b.str_due_date ASC";
	}
	
//        $filterClass = " and b.account_grade_id = '$clVal' " ;

$tomorrow = mktime(0, 0, 0, date("m"), date("d")+1, date("Y"));	

$tdt=date("Y-m-d", $tomorrow);





 // drupal_set_message(t("Class Filter, $tdt "));	



db_set_active('qtxt_db');	

   $sql = "select b.teacher_name,b.grade_name,b.student_name,b.message,b.str_due_date,b.teacher_message_id from {qtxt_sms_teacher_messages_v2} b 

	 where (b.due_date = curdate() or b.due_date ='$tdt')  and b.process_flag = 1 and b.type_id = 3 " . $filterClass; 


	   

     $query_count = "select count(teacher_message_id) from {qtxt_sms_teacher_messages_v2} b 

	 where b.process_flag = 1 and b.account_student_map_id is null "  . $filterClass ; 

	     

	 $sql .= tablesort_sql($header);



   $result = pager_query($sql, 100, 5, $query_count);



  



     $form['access'] = array(

    '#type' => 'fieldset',

    '#title' => t('Access log settings'),

    '#tree' => TRUE,

	'#visible' => false,

  );  




  $account = array();



$i = 1;  

  while ($account = db_fetch_object($result)) {

	$form['access']['account'][$i] = array(

//		'#type' => 'checkbox',

		'#return_value' => $account->file_name,

		'#return_value' => $account->teacher_message_id,

		'#default_value' => 0,

		'#tree' => TRUE,

		'#disabled' => True,



	  );

$file_name = $account->file_name;

// "<a href='#' id='check_name'>" . t('Check Product Name') . "</a><br/>",

 // $name = "<a href='newcampusonline.com/demo/sites/default/files/' . $file_name . '>"'  . $file_name . "</a>";



// drupal_set_message(t("File Name , $name"));	

		

  //  $form['access']['teachername'][$account->teacher_message_id] = array('#value' => $account->teacher_name);

  //  $form['access']['studentname'][$account->teacher_message_id] = array('#value' => $account->student_name);

 $form['access']['gradename'][$account->teacher_message_id] = array('#value' => $account->grade_name);
	

	$form['access']['message'][$account->teacher_message_id] =  array('#value' => $account->message);
	
	
	$form['access']['duedate'][$account->teacher_message_id] =  array('#value' => $account->str_due_date);

   // $form['access']['filename'][$account->teacher_message_id] =  array('#value' => $account->file_name);

    
	//$form['access']['msgcreationdate'][$account->teacher_message_id] =  array('#value' => $account->msg_creation_date);

   //  $form['access']['accountstudentid'][$account->teacher_message_id] =  array('#value' => $account->teacher_message_id);

	  $form['access']['accountstudentid'][$account->teacher_message_id] =  array('#type' => 'hidden','#value' => $account->teacher_message_id);


	$i = $i + 1;

  }

db_set_active('default');



   $form['pager'] = array('#value' => theme('pager', NULL, 6, 0));

  $form['#theme'] = 'v3_hwork_my_form1_theme';   

  $form['totalcount'] = array(

	'#type' => 'hidden', '#default_value' => ($i  -1 )

  );  

  return $form;

}



function theme_v3_hwork_my_form1_theme($form)

{

$rows = array();

$i = 1;

foreach(element_children($form['access']['accountstudentid']) as $key) {

	$row = array(); 

       //$row[] =  drupal_render($form['access']['account'][$i]);

	 //  $row[] =  drupal_render($form['access']['teachername'][$key]);
	   
	   $row[] =  drupal_render($form['access']['gradename'][$key]);


       $row[] =  drupal_render($form['access']['message'][$key]);

       $row[] =  drupal_render($form['access']['duedate'][$key]);
$row[] =   l(t('More info'), 'hwork');
	 
if  (isset( $form['access']['filename'][$key]['#value'])) {
//              $row[] =   l(t('File'), 'sites/default/files/'. $form['access']['filename'][$key]);
              $row[] =   l($form['access']['filename'][$key]['#value'], 'sites/default/files/'. $form['access']['filename'][$key]['#value']);
         } else {
         $row[] =  drupal_render(   $form['access']['filename'][$key]);
         }
 

      // $row[] =  drupal_render($form['access']['msgtype'][$key]);

     //  $row[] =  drupal_render($form['access']['msgcreationdate'][$key]);

	  //  $row[] =  drupal_render($form['access']['accountstudentid'][$key]);

	   $rows[] = $row; 

	$i = $i +1 ;


}



if(count($rows)){

			$header = array(

				// theme('table_select_header_cell'), t('Teacher Name'), t('Message'), t('Due Date'));
       t('Grade'), t('Message'), t('Due Date'), t('More Info'), t(' '));

  }

  else{

    $header = array(t(''), t('')); 

    $row = array();

    $row[] = array

    (

      'data' => t('No Data Found for the Selected Criteria'),

      'colspan' => 2,

      'style' => 'text-align:center'

    );

    $rows[] = $row;

  }

$output = theme('table', $header, $rows); 
$output .= drupal_render($form['options']); 

//return $output . drupal_render($form); 
return $output ;

}  
