<?php







/**







 * Implementation of hook_views_api().







 *







 */







// require ( "../quadroquest/svrs/QtxtSVRSLibrary.php");















function v3_academic_arrear_info_stu_views_api() {







  return array(







    'api' => 2,







    'path' => drupal_get_path('module', 'v3_academic_arrear_info_stu'),







  );







}



function v3_academic_arrear_info_stu_menu() {







	



	$items['sar'] = array(







			 'title' => t('Arrear Report'),







			'page callback' => 'v3_academic_arrear_stu_form',







			'type' => MENU_CALLBACK,







			'access callback' => 'user_access',







			'access arguments' => array('access content'),







	);	







	return $items;







	}







	















function v3_academic_arrear_stu_form() {







			$output = drupal_get_form('v3_academic_arrear_stu_filter_form');







	//		 $output .= drupal_get_form('v3_academic_arrear_stu_my_form');







			return $output ;







}



function v3_academic_arrear_stu_filter_form($form_state) {



global $user;



$profile =  profile_load_profile($user);



$myMobileNumber =  $user->profile_mobile; 



$uid = $user->uid;






		if(!empty($_SESSION['user_section_filter_value'])) {

			$c2Val = &$_SESSION['user_section_filter_value'];

		} else {

			$c2Val = "";

		}




$_SESSION['user_section_filter_value'] = $c2Val;







 $i = 0;

 





  $form['filters'] = array(



    '#type' => 'fieldset',



    '#title' => t('Filter'),



    // '#theme' => 'user_filters',



  );



	db_set_active('qtxt_db');	



$result = db_query("select account_test_map_id,test_code from {qtxt_sms_account_test_map} where account_id =5 ");



$sectionoptions = array('' => t('Select..'));







while ($row = db_fetch_object($result)) {



  $sectionoptions[$row->account_test_map_id ] =  $row->test_code; //This is the only line that changed from the code above.



}



db_set_active('default');







$key = 'section';				



 $names[$key] = 'Code';



 $form['filters']['status'][$key] = array(



      '#type' => 'select',


'#title' => 'Examination',




      '#options' => $sectionoptions,



    );




$form['filters']['status']['section']['#default_value']	= $c2Val;  



  







 $form['filters']['buttons']['submit'] = array(



    '#type' => 'submit',



    '#value' => t('Apply'),

    '#prefix' => '<br/>'



  );


$form['filters']['buttons']['submit']['#attributes']['class']  = $form['filters']['buttons']['submit']['#attributes']['class'] . ' qbsubmit';


return $form;



}



function v3_academic_arrear_stu_filter_form_submit($form, &$form_state) {

global $user;

$profile =  profile_load_profile($user);

$myMobileNumber =  $user->profile_mobile; 

$uid = $user->uid;

// $val2 = $form_state['values'][ 'class'];

$val3=  $form_state['values']['section'];

  $op = $form_state['values']['op'];

  switch ($op) {

    case t('Apply'): 

case t('Apply'): 


	  if (isset($form_state['values'][ 'section'])) {



			$filter = $form_state['values'][ 'section'];

		//	drupal_set_message(t("After Submit, Value Selected $filter "));	  

$_SESSION['user_section_filter_value'] = $filter;



      } else  {



		//	drupal_set_message(t("In the Filter, Class not selected"));	  

	  }





	  break;



	

    case t('Undo'):

//      array_pop($_SESSION['user_overview_filter']);

      break;

    case t('Reset'):

//      $_SESSION['user_overview_filter'] = array();

      break;

    case t('Delete'):

      return;

  }



  
 if($val3 == null)
{
$form_state['redirect'] = "sar/$uid";
return;
}
$form_state['redirect'] = "sar/$uid/$val3";
  return;
}