<?php



/**



 * Implementation of hook_views_api().



 *



 */



// require ( "../quadroquest/svrs/QtxtSVRSLibrary.php");







function v3_questionbank_info_views_api() {



  return array(



    'api' => 2,



    'path' => drupal_get_path('module', 'v3_questionbank_info'),



  );



}

function v3_questionbank_info_menu() {



	

	$items['qbank'] = array(



			'title' => t('Question Bank'),



			'page callback' => 'v3_questionbank_form',



			'type' => MENU_CALLBACK,



			'access callback' => 'user_access',



			'access arguments' => array('access content'),



	);	



	return $items;



	}


function v3_questionbank_form() {



			$output = drupal_get_form('v3_questionbank_filter_form');



			 $output .= drupal_get_form('v3_questionbank_my_form');



			return $output ;



}

function v3_questionbank_filter_form($form_state) {

global $user;

$profile =  profile_load_profile($user);

$myMobileNumber =  $user->profile_mobile; 

$uid = $user->uid;

if(!empty($_SESSION['user_class_filter_value'])) {
			$clVal = &$_SESSION['user_class_filter_value'];
		} else {
			$clVal = "";
		}
		if(!empty($_SESSION['user_section_filter_value'])) {
			$c2Val = &$_SESSION['user_section_filter_value'];
		} else {
			$c2Val = "";
		}

$_SESSION['user_class_filter_value'] = $clVal;

$_SESSION['user_section_filter_value'] = $c2Val;



 $i = 0;
 


  $form['filters'] = array(

    '#type' => 'fieldset',

    '#title' => t('Filters'),

    // '#theme' => 'user_filters',

  );



db_set_active('qtxt_db');	

$result = db_query("select account_grade_id,grade_name from {v3_question_bank} ");

$options = array('' => t('Select..'));

while ($row = db_fetch_object($result)) {

  $options[$row->account_grade_id] =  $row->grade_name; 

  // This is the only line that changed from the code above.

}

  

$key = 'class';				

$names[$key] = 'Name';

    $form['filters']['status'][$key] = array(



      '#type' => 'select',

      '#options' => $options,
'#title' => t('Class'),

    );

	db_set_active('qtxt_db');	

$result = db_query("select distinct(q_subject) from {v3_question_bank}");

$sectionoptions = array('' => t('Select..'));



while ($row = db_fetch_object($result)) {

  $sectionoptions[$row->q_subject ] =  $row->q_subject; //This is the only line that changed from the code above.

}

db_set_active('default');



$key = 'section';				

 $names[$key] = 'Code';

 $form['filters']['status'][$key] = array(

      '#type' => 'select',

 '#title' => t('Subject'),

      '#options' => $sectionoptions,

    );


$form['filters']['status']['class']['#default_value']	= $clVal;

$form['filters']['status']['section']['#default_value']	= $c2Val;  

  



 $form['filters']['buttons']['submit'] = array(

    '#type' => 'submit',

    '#value' => t('Apply'),

    '#prefix' => '<br/>',

  );
$form['filters']['buttons']['submit']['#attributes']['class']  = $form['filters']['buttons']['submit']['#attributes']['class'] . ' qbsubmit';

return $form;

}

function v3_questionbank_filter_form_submit($form, &$form_state) {
global $user;
$profile =  profile_load_profile($user);
$myMobileNumber =  $user->profile_mobile; 
$uid = $user->uid;
$val2 = $form_state['values'][ 'class'];
$val3=  $form_state['values']['section'];
  $op = $form_state['values']['op'];
  switch ($op) {
    case t('Apply'): 
case t('Apply'): 

      if (isset($form_state['values'][ 'class'])) {

			$filter = $form_state['values'][ 'class'];
			// drupal_set_message(t("After Submit, Value Selected $filter "));	  

			$_SESSION['user_class_filter_value'] = $filter;

      } else  {

		//	drupal_set_message(t("In the Filter, Class not selected"));	  
	  }
	  if (isset($form_state['values'][ 'section'])) {

			$filter = $form_state['values'][ 'section'];
			// drupal_set_message(t("After Submit, Value Selected $filter "));	  
                    $_SESSION['user_section_filter_value'] = $filter;

      } else  {

		//	drupal_set_message(t("In the Filter, Class not selected"));	  
	  }


	  break;

	
    case t('Undo'):
//      array_pop($_SESSION['user_overview_filter']);
      break;
    case t('Reset'):
//      $_SESSION['user_overview_filter'] = array();
      break;
    case t('Delete'):
      return;
  }

   $form_state['redirect'] = 'qbank';
  return;
}

function v3_questionbank_my_form($form_state) {
global $user;
$profile =  profile_load_profile($user);
$myMobileNumber =  $user->profile_mobile; 
$uid = $user->uid;

  $header = array(
    array(),
    array('data' => t('testid'), 'field' => 'b.questions'),
    array('data' => t('subject'), 'field' => 'b.Answers'),
    array('data' => t('subject'), 'field' => 'b.qid'),
    
  );

$clVal = &$_SESSION['user_class_filter_value'] ;
$c2Val = &$_SESSION['user_section_filter_value'] ;

// drupal_set_message(t("Class Filter 1 , $clVal,$c2Val"));	
  

if  ( ( ! isset($clVal) )|| ( $clVal == "" ) ) {
		$accountArray = "";
		// drupal_set_message(t("log 2 c1Val Not Set "));	
		db_set_active('qtxt_db');	

		$result = db_query("select account_grade_id,grade_name from {v3_question_bank}");

		$accountGradeId = array();

		while ($row = db_fetch_object($result)) {

		  $accountGradeId[] =  $row->account_grade_id; 
		  // This is the only line that changed from the code above.
		}
		db_set_active('default');
		
		if (  count( $accountGradeId ) > 0 ) {
			$accountArray = join( ",", $accountGradeId );
		}
		$filterClass = "  b.account_grade_id in (" . $accountArray . " ) ";
	} else {
		$filterClass = "  b.account_grade_id = '$clVal' ";
	}
	if  ( ( ! isset($c2Val) )|| ( $c2Val == "" ) ) {
		$accountArray = "";
		// drupal_set_message(t("log 2 c1Val Not Set "));	
		db_set_active('qtxt_db');	

		$result = db_query("select distinct(q_subject) from {v3_question_bank} ");


		$typeId = array();

		while ($row = db_fetch_object($result)) {

		  $testId[] =  $row->q_subject; 
		  // This is the only line that changed from the code above.
		}
		db_set_active('default');
		
		if (  count( $testId ) > 0 ) {
			$accountArray = join( ",", $testId);
		}

		$filterSection = " and b.q_subject in('English','Maths','Science','social')";
		
		
		// drupal_set_message (t("Type $accountArray"));
	} else {
		$filterSection = " and b.q_subject = '$c2Val' ";
	}

	





//drupal_set_message(t("Class Filter, $filterClass"));	

  db_set_active('qtxt_db');	
  
  $sql = "select b.qid,b.questions,b.Answers from {v3_question_bank} b where  " . $filterClass . $filterSection."order by qid desc" ; 
	 
	   
     $query_count = "select count(b.qid) from {v3_question_bank} b where  " . $filterClass . $filterSection."order by qid desc";
	
     
	 $sql .= tablesort_sql($header);

   $result = pager_query($sql, 25, 0, $query_count);

  $account = array();

$i = 1;  
  while ($account = db_fetch_object($result)) {
	$form['access']['account'][$i] = array(
//		'#type' => 'checkbox',
		'#return_value' => $account->qid,
		'#default_value' => 0,
		'#tree' => TRUE,
              '#disabled'=>'false',

	  );
    $form['access']['question'][$account->qid] =  array('#value' => $account->questions);
    $form['access']['answer'][$account->qid] =  array('#value' => $account->Answers);
    $form['access']['quid'][$account->qid] = array('#type' => 'hidden','#value' => $account->qid);
    
	$i = $i + 1;
  }
db_set_active('default');

  $form['pager'] = array('#value' => theme('pager', NULL, 25, 0));
  $form['#theme'] = 'v3_questionbank_my_form_theme';   
  $form['totalcount'] = array(
	'#type' => 'hidden', '#default_value' => ($i  -1 )
  );  
  return $form;
}

function v3_questionbank_info_theme() {
	return array(
		'v3_questionbank_my_form_theme' => array('arguments'=> array('form' => NULL),),
		);
}


function theme_v3_questionbank_my_form_theme($form)
{
$rows = array();
$i = 1;
foreach(element_children($form['access']['quid']) as $key) {
	$row = array(); 
       $row[] =  drupal_render($form['access']['account'][$i]);
       $row[] =  drupal_render($form['access']['question'][$key]);
	 $row[] =  drupal_render($form['access']['answer'][$key]);

       $rows[] = $row; 
	$i = $i +1 ;
}

if(count($rows)){
	$header = array(t(''),t('Question'), t('Answer'));

  }
  else{
    $header = array(t(''), t('')); 
    $row = array();
    $row[] = array
    (
      'data' => t('No Data Found for the Selected Criteria'),
      'colspan' => 2,
      'style' => 'text-align:center'
    );
    $rows[] = $row;
  }
$output = theme('table', $header, $rows); 
return $output . drupal_render($form); 
}  



