<?php



/**



 * Implementation of hook_views_api().



 *



 */



// require ( "../quadroquest/SMSLibrary.php");







function v3_cce_mark_report_pv_views_api() {



  return array(



    'api' => 2,



    'path' => drupal_get_path('module', '  '),



  );



}











function v3_cce_mark_report_pv_menu() {



	$items['markreport_pv'] = array(



			'title' => t('Mark Report'),



			'page callback' => 'cce_mark_report_pv_form',



			'type' => MENU_CALLBACK,



			'access callback' => 'user_access',



			'access arguments' => array('access content'),



	);



	



return $items;



}







function cce_mark_report_pv_form() {



			$output = drupal_get_form('cce_mark_pv_form');



			return $output ;



}















function cce_mark_pv_form( $form_state) {







global $user;



$profile =  profile_load_profile($user);



$myMobileNumber =  $user->profile_mobile;  

$uid = $user->uid;







$defusermobile = $myMobileNumber;



$defadminuserid = "";



$defadminpwd = "";











	  $form['adminOuter'] = array(



						'#type' => 'fieldset',



						'#title' => t('Scholastic and Co Scholastic Mark Details '),



						'#collapsible' => TRUE, 



						'#collapsed' => FALSE,



						'#tree' => TRUE



	  );



				  







	  db_set_active('qtxt_db');	







	  



	  $resultg1 = db_query("select account_student_map_id,student_name from 

	  {qtxt_sms_mobile_students_v} where drupal_uid =$uid  order by SUBSTRING(student_name, LOCATE('.', student_name)+1)");



				  $igradeOptions = array('' => t('Select..'));



				  while ($rowg1 = db_fetch_object($resultg1)) {



				  	$igradeOptions[$rowg1->account_student_map_id ] =  $rowg1->student_name; //This is the only line that changed from the code above.



				  	}



				db_set_active('default');



				  $form['adminOuter']['grade'] = array('#type' => 'select',



				  				  		'#options' => $igradeOptions,



				  				  		'#title' => t('Student Name'),



				  				  		'#description' => t('Please select the Student Name'),



				  				  		'#disabled' => FALSE,



				  				  		



				  );

	  



				



  $form['adminOuter']['submit'] = array(



    '#type' => 'submit',



    '#value' => t('Mark Summary Details'),



  );

$form['adminOuter']['marks'] = array(



    '#type' => 'submit',



    '#value' => t('Mark Details'),



  );





return $form;



 



}

function cce_mark_pv_form_submit($form, &$form_state) {

$op = $form_state['values']['op'];

 

	global $user;



	$profile =  profile_load_profile($user);



	$myMobileNumber =  $user->profile_mobile; 



	$uid = $user->uid;



	// $_SESSION['t_student'] = $form_state['values']['adminOuter']['student'];

	$_SESSION['t_student_grade'] = $form_state['values']['adminOuter']['grade'];

	$grade = &$_SESSION['t_student_grade'];



db_set_active('qtxt_db');	



		$result = db_query("select distinct(account_grade_id) FROM {qtxt_sms_mobile_students_v} where drupal_uid =$uid and account_student_map_id =$grade");



		$typeId = array();



		while ($row = db_fetch_object($result)) {



		  $typeId[] =  $row->account_grade_id; 

		  // This is the only line that changed from the code above.

		}

		db_set_active('default');

		

		if (  count( $typeId ) > 0 ) {

			$accountArray = join( " ", $typeId );

		}

		$filterSection =  "$accountArray"  ;







	if(!empty($_SESSION['t_student_grade'])) {



		$grade = &$_SESSION['t_student_grade'];



	} else {



		$grade = "";



	}



	// drupal_set_message(t("g $grade"));

      //  drupal_set_message(t("s $student"));

 





if ( $op == "Mark Summary Details" )

{



	$form_state['redirect'] = "ccemarksdetrpt/$filterSection/$grade";



  return;

}





if ( $op == "Mark Details" )

{



	$form_state['redirect'] = "ccescholasticreport/$filterSection/$grade";



  return;

}









}





