<?php



/**



 * Implementation of hook_views_api().



 *



 */



// require ( "../quadroquest/SMSLibrary.php");







function v3_cce_download_pdf_report_views_api() {



  return array(



    'api' => 2,



    'path' => drupal_get_path('module', ' '),



  );



}











function v3_cce_download_pdf_report_menu() {



	$items['downloadpdf'] = array(



			'title' => t('Download Report Card in PDF'),



			'page callback' => 'cce_download_pdf_report_form',



			'type' => MENU_CALLBACK,



			'access callback' => 'user_access',



			'access arguments' => array('access content'),



	);



	$items['downloadpdf/ind/ahahjs2'] = array(



        'page callback' => 'cce_download_ahah_field_js_for_ind2',



    //    'access arguments' => array('administer ahahtestmodule'),



        'type' => MENU_CALLBACK,



    			'access callback' => 'user_access',



    			'access arguments' => array('access content'),	



  );



return $items;



}







function cce_download_pdf_report_form() {



			$output = drupal_get_form('cce_download_form');

			$output .= drupal_get_form('cce_download_my_form');

			



			return $output ;



}















function cce_download_form( $form_state) {







global $user;



$profile =  profile_load_profile($user);



$myMobileNumber =  $user->profile_mobile;  







$defusermobile = $myMobileNumber;



$defadminuserid = "";



$defadminpwd = "";











	  $form['adminOuter'] = array(



						'#type' => 'fieldset',



						'#title' => t('Download Report Card In PDF Format '),



						'#collapsible' => TRUE, 



						'#collapsed' => FALSE,



						'#tree' => TRUE



	  );



				  







	  db_set_active('qtxt_db');	







	  



	  $resultg1 = db_query("SELECT account_grade_id,grade_name FROM {qtxt_sms_account_grades} a, {qtxt_sms_account} b where   a.account_id = b.account_id and section != 'ALL' order by class_weight ");



				  $igradeOptions = array('' => t('Select..'));



				  while ($rowg1 = db_fetch_object($resultg1)) {



				  	$igradeOptions[$rowg1->account_grade_id ] =  $rowg1->grade_name; //This is the only line that changed from the code above.



				  	}



				db_set_active('default');



				  $form['adminOuter']['grade'] = array('#type' => 'select',



				  				  		'#options' => $igradeOptions,



				  				  		'#title' => t('Class - Section'),



				  				  		'#description' => t('Please select the Department and Year '),



				  				  		'#disabled' => FALSE,



				  				  		'#ahah' => array(



				  				  		 'path' => 'downloadpdf/ind/ahahjs2',



				  				  		 'wrapper' => 'ahah-wrapper-grade',



				  				  		 'method' => 'replace',



				  				  						)



				  );



				  



				  $form['adminOuter']['student'] = array('#type' => 'select',



				  				  		'#title' => t('Student Name'),



										'#options' =>  array( '' => t('Select ..') ),



				  				  		'#description' => t('Please select the Student'),



				  				  		'#disabled' => FALSE,



				  				  	'#prefix' => '<div id = "ahah-wrapper-grade">',



				  					'#suffix' => '</div>',



				  				  		



				  );



				  



				



  $form['adminOuter']['submit'] = array(



    '#type' => 'submit',



    '#value' => t('Download Report Card'),

    '#prefix' => '<br/>',



  );



$form['adminOuter']['submit']['#attributes']['class']  = $form['adminOuter']['submit']['#attributes']['class'] . ' qbsubmit';


return $form;



 



}

function cce_download_form_validate($form, &$form_state) {
$grade  = $form_state['values']['adminOuter']['grade'];

if($grade = '')
{
form_set_error('', t('please select the class'));
}
}
function cce_download_form_submit($form, &$form_state) {

$op = $form_state['values']['op'];

 

	global $user;



	$profile =  profile_load_profile($user);



	$myMobileNumber =  $user->profile_mobile; 



	$uid = $user->uid;



	$_SESSION['t_student'] = $form_state['values']['adminOuter']['student'];



	$_SESSION['t_student_grade'] = $form_state['values']['adminOuter']['grade'];



	if(!empty($_SESSION['t_student'])) {



		$student = &$_SESSION['t_student'];



	} else {



		$student = 'null';



	}







	if(!empty($_SESSION['t_student_grade'])) {



		$grade = &$_SESSION['t_student_grade'];



	} else {



		$grade = "";



	}



//	drupal_set_message(t("g $grade"));

//       drupal_set_message(t("s $student"));





	$form_state['redirect'] = "downloadpdf";



  return;



}

function cce_download_my_form( $form_state) {

global $user;

$profile =  profile_load_profile($user);

$myMobileNumber =  $user->profile_mobile;  



  $header = array(

    array(),

    array('data' => t('Group Name'), 'field' => 'b.standard'),

    array('data' => t('Group Description'), 'field' => 'b.section'),

	t('Operations'),

  );



$clVal = &$_SESSION['t_student'] ;

$c2Val = &$_SESSION['t_student_grade'] ;



// drupal_set_message(t("student - $clVal"));	

// drupal_set_message(t("grade - $c2Val"));	





  

$filterClass = "";

    if ( $c2Val != "" ) {

		

			$filterClass = " and b.account_grade_id = $c2Val";

	} else {

			$filterClass = " and b.account_grade_id = b.account_grade_id ";

	}

	$filterSection = "";

    if ( $clVal != "" ) {

		

			$filterSection = " and b.account_student_map_id = $clVal";

	} else {

			$filterSection = " and b.account_student_map_id = b.account_student_map_id ";

	}



  db_set_active('qtxt_db');	

  $sql = "select b.account_student_map_id, b.grade_name, b.student_name,b.file_name  from  {cce_pdf_downloadd_v} b 

  where 1 = 1  " . $filterClass  . $filterSection  ; 

  $query_count = "select COUNT(account_student_map_id) from  {cce_pdf_downloadd_v} b  where 1 = 1" . $filterClass . $filterSection ;

   $sql .= tablesort_sql($header);



  $result = pager_query($sql, 1000, 0, $query_count);

  db_set_active('default');






/*
    $form['access'] = array(

    '#type' => 'fieldset',

    '#title' => t('Access log settings'),

    '#tree' => TRUE,

	'#visible' => false,

  );


*/


  $accounts = array();



$i = 1;  

  while ($account = db_fetch_object($result)) {



  $form['access']['account'][$i] = array(

		'#type' => 'checkbox',

		'#return_value' => $account->account_student_map_id,

		'#default_value' => 0,

		'#tree' => TRUE,



	  );

    $form['access']['studentname'][$account->account_student_map_id] = array('#value' => $account->student_name);

    $form['access']['gradename'][$account->account_student_map_id] =  array('#value' => $account->grade_name);

	$options = array(

			   'attributes' => array(),

			   'html' => TRUE,

	);

$pdf_file = $account->file_name;
	$form['access']['operations'][$account->account_student_map_id] = array('#value' => l('<img src="fpdf/pdficon_large.png" alt="" />', "sites/default/files/report_card/$pdf_file", $options)); 

	//	$form['access']['operations'][$account->account_student_map_id] = array('#value' => l(t('Download Pdf File'), "sites/default/files/report_card/$account->file_name", array('query' => $destination)));	

	$form['access']['studentid'][$account->account_student_map_id] =  array('#type' => 'hidden','#value' => $account->account_student_map_id);

	$i = $i + 1;

  }

// db_set_active('default');



  $form['pager'] = array('#value' => theme('pager', NULL, 100, 0));

  $form['#theme'] = 'cce_pdf_theme';   

  $form['totalcount'] = array(

	'#type' => 'hidden', '#default_value' => ($i  -1 )

  );  

  return $form;





}



function v3_cce_download_pdf_report_theme() {

	return array(

		'cce_pdf_theme' => array('arguments'=> array('form' => NULL),),

	);

}



function theme_cce_pdf_theme($form)

{

$rows = array();

$i = 1;

foreach(element_children($form['access']['studentid']) as $key) {

	$row = array(); 

//       $row[] =  drupal_render($form['access']['account'][$i]);

       $row[] =  drupal_render($form['access']['studentname'][$key]);


       $row[] =  drupal_render($form['access']['gradename'][$key]);

       $row[] =  drupal_render($form['access']['operations'][$key]);

      	$rows[] = $row; 

	$i = $i +1 ;

}



if(count($rows)){

//			$header = array( theme('table_select_header_cell'), t('Group Name'), t('Group Desc'), t('Group Id') );

				$header = array(  t('Student Name'), t('Class'), t('File Name') );

				

				//  $header[] = array('data' => t('Operations'), 'colspan' => 2);

  }

  else{

    $header = array(t('Group Name'), t('Group description')); 

    $row = array();

    $row[] = array

    (

      'data' => t('No Files were found to download '),

      'colspan' => 2,

      'style' => 'text-align:center'

    );

    $rows[] = $row;

  }

$output = theme('table', $header, $rows); 

//$output .= drupal_render($form['options']); 

// $output .= drupal_render($form['options']['submit']); 

  $form['access']['#access'] = false;

 return $output . drupal_render($form); 

 return $output ; 

}  











function cce_download_ahah_field_js_for_ind2 () {



//  krumo($form_state);



$form_state = array('storage' => NULL, 'submitted' => FALSE);



		$form_build_id = $_POST['form_build_id'];







		// Get for the form from the cache



		$form = form_get_cache($form_build_id, $form_state);



  



		// Get the form set up to process



		$args = $form['#parameters'];



		$form_id = array_shift($args);



		$form_state['post'] = $form['#post'] = $_POST;



//		$form['#programmed'] = $form['#redirect'] = FALSE;











		$gid = $form['#post']['adminOuter']['grade'];



		db_set_active('qtxt_db');



		$sqlg = " select account_student_map_id,student_name from {qtxt_sms_mobile_students_v} where account_grade_id = $gid order by SUBSTRING(student_name, LOCATE('.', student_name)+1) ";



		$resultg = db_query($sqlg);



		$valueg[''] = 'Select a value';



		while($datag = db_fetch_object($resultg))



		{



		$valueg[$datag->account_student_map_id] = $datag->student_name;



		}



		db_set_active('default');



		//$valueg1 = drupal_map_assoc($valueg);



		$form['adminOuter']['student']['#options'] = $valueg;



		form_set_cache($form_build_id, $form, $form_state);



				$form += array(



					'#post' => $_POST,



					'#programmed' => FALSE,



				  );



				$form = form_builder('qtext1_smsform', $form, $form_state);		



				$output = $form['adminOuter']['student'];



				unset($output['#prefix'],$output['#suffix']);



				$out1 =  drupal_render($output);



				drupal_json(array('status' => TRUE, 'data' => $out1));











}



