<?php



/**



 * Implementation of hook_views_api().



 *



 */



// require ( "../quadroquest/SMSLibrary.php");







function v3_leaveletter_approval_report_sent_to_parent_views_api() {



  return array(



    'api' => 2,



    'path' => drupal_get_path('module', '  '),



  );



}



function v3_leaveletter_approval_report_sent_to_parent_menu() {



	$items['report1'] = array(



			'title' => t('Leave Letter Reports Sent by Teacher'),



			'page callback' => 'v3_leaveletter_approval_report_sent_to_parent_form',



			'type' => MENU_CALLBACK,



			'access callback' => 'user_access',



			'access arguments' => array('access content'),



	);



	



	$items['report/next'] = array(



			'title' => t('Are you Sure to Delete the Reports'),



			'page callback' => 'ver3_teacher_leaveletter_report_my_form',



			'type' => MENU_CALLBACK,



			'access callback' => 'user_access',



			'access arguments' => array('access content'),



	);	



	



	return $items;



	







}







	



function v3_leaveletter_approval_report_sent_to_parent_form() {



			$output = drupal_get_form('v3_leaveletter_approval_report_sent_to_parent_filter_form');



			 $output .= drupal_get_form('v3_leaveletter_approval_report_sent_to_parent_my_form');



			return $output ;



          }



		  



function v3_leaveletter_approval_report_sent_to_parent_filter_form($form_state) {



global $user;



$profile =  profile_load_profile($user);



$myMobileNumber =  $user->profile_mobile; 



$uid = $user->uid;



$c2Val;







		if(!empty($_SESSION['user_class_filter_value'])) {



			$clVal = &$_SESSION['user_class_filter_value'];



		} else {



			$clVal = "";



		}



		if(!empty($_SESSION['user_section_filter_value'])) {



			$c2Val = &$_SESSION['user_section_filter_value'];



		} else {



			$c2Val = "";



		}







	$_SESSION['user_class_filter_value'] = $clVal;



	$_SESSION['user_section_filter_value'] = $c2Val;















 $i = 0;



  $form['filters'] = array(



    '#type' => 'fieldset',



    '#title' => t('Filter'),



  //  '#theme' => 'user_filters',



  );







  



db_set_active('qtxt_db');	







$result = db_query("select distinct(account_grade_id),grade_name from {qtxt_sms_staff_mobile_v} where drupal_uid = $uid");



$options = array('' => t('Select..'));



while ($row = db_fetch_object($result)) {



  $options[$row->account_grade_id ] = $row->grade_name; 
 


  // This is the only line that changed from the code above.



}



 db_set_active('default');



  



  $form['filters']['class'] = array(




 '#title' => t('Department'),


	  '#type' => 'select',



      '#options' => $options,



    );



	



	



$form['filters']['class']['#default_value']	= $clVal;











 
$form['filters']['buttons']['submit'] = array(



    '#type' => 'submit',



    '#value' => t('Apply'),

 '#prefix' => '<br/>',



  );

 $form['filters']['buttons']['submit']['#attributes']['class']  = $form['filters']['buttons']['submit']['#attributes']['class'] . ' qbsubmit';
return $form;







}



function v3_leaveletter_approval_report_sent_to_parent_filter_form_submit($form, &$form_state) {



global $user;



$profile =  profile_load_profile($user);



$myMobileNumber =  $user->profile_mobile; 



$uid = $user->uid;







  $op = $form_state['values']['op'];





  switch ($op) {



   case t('Apply'): 

	   if (isset($form_state['values']['class'])) {



			$filter = $form_state['values']['class'];


			$_SESSION['user_class_filter_value'] = $form_state['values']['class'];



      } else  {



		  $_SESSION['user_class_filter_value'] = "";	



		  unset ( $_SESSION['user_class_filter_value'] );



		  



	  }



	  



	  



	  



	  break;



    case t('Undo'):



//      array_pop($_SESSION['user_overview_filter']);



      break;



    case t('Reset'):



//      $_SESSION['user_overview_filter'] = array();



      break;



    case t('Delete'):



      return;



  }







  $form_state['redirect'] = 'report1';



  return;



}



function v3_leaveletter_approval_report_sent_to_parent_my_form($form_state) {



global $user; 



$profile =  profile_load_profile($user);



$myMobileNumber =  $user->profile_mobile; 



$uid = $user->uid;







  $header = array(



    array(),



    array('data' => t('Student Name'), 'field' => 'student_name'),

 array('data' => t('Parent message id'), 'field' => 'parent_message_id'),


 //   array('data' => t(' '), 'field' => 'teacher_name'),



    array('data' => t('Message'), 'field' => 'message'),



	array('data' => t('Delivery Report'), 'field' => 'delivery_report'),



    array('data' => t('Reason'), 'field' => 'comments'),



	 



	



  );







$clVal = &$_SESSION['user_class_filter_value'] ;




$filterClass = "";











	 if  ( ( ! isset($clVal) )|| ( $clVal == "" ) ) {



			$accountArray = "";



		db_set_active('qtxt_db');	







		$result = db_query("select distinct(account_grade_id) from {qtxt_sms_staff_mobile_v} where drupal_uid = $uid ");







		$accountGradeId = array();







		while ($row = db_fetch_object($result)) {







		  $accountGradeId[] =  $row->account_grade_id; 



		  // This is the only line that changed from the code above.



		}



		db_set_active('default');



		



		if (  count( $accountGradeId ) > 0 ) {



			$accountArray = join( ",", $accountGradeId );



		}



		$filterClass = " and account_grade_id in (" . $accountArray . " ) ";



	} else {



		$filterClass = " and account_grade_id = '$clVal' ";



	}




  db_set_active('qtxt_db');	



  



 



$sql = "select distinct(student_name),teacher_name,message,delivery_report,comments,parent_message_id,str_msg_creation_date  from {qtxt_sms_parent_messages_bkp_v5} where ((process_flag = 4) or (process_flag = 1))  and type_id = 4 and delivery_report != 'Request is Pending' " . $filterClass." order by parent_message_id desc" ; 







$query_count = "select count(parent_message_id) from {qtxt_sms_parent_messages_bkp_v5}  



	 where (( process_flag = 0) or (process_flag = 1)) and type_id =4 " . $filterClass ." order by parent_message_id desc"  ; 




$sql .= tablesort_sql($header);


   $result = pager_query($sql, 25, 0, $query_count);



    $form['access'] = array(



    '#type' => 'fieldset',



    '#title' => t('Access log settings'),



    '#tree' => TRUE,



	'#visible' => false,



  );  







  $account = array();







$i = 1;  



  while ($account = db_fetch_object($result)) {



	$form['access']['account'][$i] = array(



		'#type' => 'checkbox',


		'#return_value' => $account->parent_message_id,



		'#default_value' => 0,



		'#tree' => TRUE,







	  );



    $form['access']['studentname'][$account->parent_message_id] = array('#value' => $account->str_msg_creation_date);



    $form['access']['teachername'][$account->parent_message_id] =  array('#value' => $account->student_name);



    $form['access']['message'][$account->parent_message_id] =  array('#value' => $account->message);



    $form['access']['msgtype'][$account->parent_message_id] =  array('#value' => $account->delivery_report);



    $form['access']['msgcreationdate'][$account->parent_message_id] =  array('#value' => $account->comments);



    $form['access']['accountgradeid'][$account->parent_message_id] =  array('#type' => 'hidden','#value' => $account->parent_message_id);



	



	$i = $i + 1;



  }



db_set_active('default');


  $form['#theme'] = 'v3_leaveletter_approval_report_sent_to_parent_my_form_theme';   



  $form['totalcount'] = array(



	'#type' => 'hidden', '#default_value' => ($i  -1 )



  );  



  return $form;



}







function v3_leaveletter_approval_report_sent_to_parent_theme() {



	return array(



		'v3_leaveletter_approval_report_sent_to_parent_my_form_theme' => array('arguments'=> array('form' => NULL),),



		'v3_leaveletter_approval_report_sent_to_parent_my_next_form_theme' => array('arguments'=> array('form' => NULL),),



	);



}



function v3_leaveletter_approval_report_sent_to_parent_my_form_submit($form,&$form_state) {











	$TotalCount = $form_state['values']['totalcount'];



	



	$myArray = array();



	



	if ( isset( $form_state['clicked_button']['#post']['access']['account'] ) ) 



	{



	$myArray = $form_state['clicked_button']['#post']['access']['account'];



	



	}



	foreach ($myArray as $key => $value) {



	}



	$_SESSION['user_total_count'] =  $TotalCount;



	$_SESSION['selectOptions'] =  $myArray;



	$selList = &$_SESSION['selectOptions'];



	



	foreach ($selList as $key => $value) {

drupal_set_message(t("Value, $value"));






	db_set_active('qtxt_db');







	



  $sql = db_query("Update qtxt_sms_parent_message_bkp set process_flag = 2  where parent_message_id = $value ") ; 











	}



	drupal_set_message(t(" Your Message has been deleted "));



	



	$form_state['redirect'] =   'report1';



	



  return;	 

 



}







function theme_v3_leaveletter_approval_report_sent_to_parent_my_form_theme($form)



{



$rows = array();



$i = 1;



foreach(element_children($form['access']['accountgradeid']) as $key) {



	$row = array(); 



       $row[] =  drupal_render($form['access']['account'][$i]);






       $row[] =  drupal_render($form['access']['teachername'][$key]);



       $row[] =  drupal_render($form['access']['message'][$key]);



      $row[] =  drupal_render($form['access']['msgtype'][$key]);



	  $row[] =  drupal_render($form['access']['msgcreationdate'][$key]);
         $row[] =  drupal_render($form['access']['studentname'][$key]);




	 // $row[] =  drupal_render($form['access']['accountgradeid'][$key]);



	   $rows[] = $row; 



	$i = $i +1 ;



}







if(count($rows)){



			$header = array(



				theme('table_select_header_cell'),t('Student Name'), t('Message'), t('Delivery Report'), t('Comments'),t('Approved On'));



  }



  else{



    $header = array(t(''), t('')); 



    $row = array();



    $row[] = array



    (



      'data' => t('No Data Found for the Selected Criteria'),



      'colspan' => 2,



      'style' => 'text-align:center'



    );



    $rows[] = $row;



  }



$output = theme('table', $header, $rows); 



//return $output . drupal_render($form); 



 $form['access']['#access'] = false;



 return $output . drupal_render($form); 



 return $output ;



}
