<?php
/**

 * Implementation of hook_views_api().
 *
 */

// require ( "../quadroquest/SMSLibrary.php");

function v3_cce_download_pdf_sv_report_views_api() {

  return array(

    'api' => 2,

    'path' => drupal_get_path('module', ' '),

  );

}

function v3_cce_download_pdf_sv_report_menu() {

	$items['downloadpdf_sv'] = array(

			'title' => t('Download Report Card in PDF'),
			'page callback' => 'cce_download_pdf_sv_report_form',
			'type' => MENU_CALLBACK,
			'access callback' => 'user_access',
			'access arguments' => array('access content'),
	);
return $items;

}

function cce_download_pdf_sv_report_form() {
			$output .= drupal_get_form('cce_download_sv_my_form');
			return $output ;

}

function cce_download_sv_my_form( $form_state) {

global $user;

$profile =  profile_load_profile($user);

$myMobileNumber =  $user->profile_mobile;  

$uid = $user->uid;


         db_set_active('qtxt_db');	

		$result = db_query("select account_student_map_id from {qtxt_sms_mobile_students_v} where drupal_uid = $uid ");

		$accountGradeId = array();

		while ($row = db_fetch_object($result)) {

		  $accountGradeId[] =  $row->account_student_map_id; 
		  		}



		db_set_active('default');		
		if (  count( $accountGradeId ) > 0 ) {
			$accountArray = join( ",", $accountGradeId );
		}
		$smId = "$accountArray";

  $header = array(

  array(),

  );


$c2Val = &$_SESSION['t_student_grade'] ;



  db_set_active('qtxt_db');	

  $sql = "select b.account_student_map_id, b.grade_name, b.student_name,b.file_name  from  {cce_pdf_downloadd_v} b where b.account_student_map_id =  $smId "; 

  $query_count = "select COUNT(account_student_map_id) from  {cce_pdf_downloadd_v} b  where b.account_student_map_id =  $smId ";

   $sql .= tablesort_sql($header);

  $result = pager_query($sql, 1000, 0, $query_count);

  db_set_active('default');

    $form['access'] = array(

    '#type' => 'fieldset',

    '#title' => t('Access log settings'),

    '#tree' => TRUE,

	'#visible' => false,

  );


  $accounts = array();

$i = 1;  

  while ($account = db_fetch_object($result)) {

  $form['access']['account'][$i] = array(

		'#type' => 'checkbox',

		'#return_value' => $account->account_student_map_id,

		'#default_value' => 0,

		'#tree' => TRUE,

	  );

    $form['access']['studentname'][$account->account_student_map_id] = array('#value' => $account->student_name);

    $form['access']['gradename'][$account->account_student_map_id] =  array('#value' => $account->grade_name);

	$options = array(

			   'attributes' => array(),

			   'html' => TRUE,
	);


	$form['access']['operations'][$account->account_student_map_id] = array('#value' => l('<img src="fpdf/pdficon_large.png" alt="" />', "sites/default/files/report_card/$account->file_name", $options)); 

	$form['access']['studentid'][$account->account_student_map_id] =  array('#type' => 'hidden','#value' => $account->account_student_map_id);

	$i = $i + 1;

  }



  $form['pager'] = array('#value' => theme('pager', NULL, 100, 0));

  $form['#theme'] = 'cce_pdf_theme';   

  $form['totalcount'] = array(

	'#type' => 'hidden', '#default_value' => ($i  -1 )

  );  



  return $form;


}


function cce_download_pdf_sv_report_theme() {

	return array(

		'cce_pdf_sv_theme' => array('arguments'=> array('form' => NULL),),
	);

}


function theme_cce_pdf_sv_theme($form)

{

$rows = array();

$i = 1;

foreach(element_children($form['access']['studentid']) as $key) {

	$row = array(); 
       $row[] =  drupal_render($form['access']['studentname'][$key]);

       $row[] =  drupal_render($form['access']['gradename'][$key]);

       $row[] =  drupal_render($form['access']['operations'][$key]);

	   $rows[] = $row; 

	$i = $i +1 ;



}


if(count($rows)){

				$header = array(  t('Student Name'), t('Class'), t('File Name') );

  }

  else{

    $header = array(t('Group Name'), t('Group description')); 

    $row = array();

    $row[] = array

    (

      'data' => t('No Files were found to download '),

      'colspan' => 2,

      'style' => 'text-align:center'

    );

    $rows[] = $row;

  }

$output = theme('table', $header, $rows); 

  $form['access']['#access'] = false;

 return $output . drupal_render($form); 

 return $output ; 

}  
