<?php

function v3_load_admindata_views_api( ) {
	return array(
		 'api' => 2,
		'path' => drupal_get_path( 'module', 'v3_load_admindata' ) 
	);
}
function v3_load_admindata_menu( ) {
	$items[ 'loadadmin' ]        = array(
		 'title' => t( 'Load Admin Data' ),
		'page callback' => 'v3_load_admindata_form',
		'type' => MENU_CALLBACK,
		'access callback' => 'user_access',
		'access arguments' => array(
			 'access content' 
		) 
	);
	return $items;
}
function v3_load_admindata_form( ) {
	$output = drupal_get_form( 'v3_load_admindata_main_form' );
	return $output;
}
function v3_load_admindata_main_form( $form_state ) {
	global $user;
	$profile        = profile_load_profile( $user );
	$myMobileNumber = $user->profile_mobile;
//	$uid            = $user->uid;
		$form[ 'loadadmindata' ] = array(
		 '#type' => 'fieldset',
		'#title' => t( 'Load School Admin Data' ),
		'#collapsible' => FALSE,
		'#collapsed' => FALSE,
		'#tree' => TRUE 
	);
	             $form[ 'loadadmindata' ]['StaffName'] = array(
				'#title' => t('Staffname'),
				'#type' => 'textfield',
				'#size' => 50,
				'#description' => t('Please Enter Staff Name.'),
				'#required' => TRUE,
				);
				
				$form[ 'loadadmindata' ]['UserName'] = array(
				'#title' => t('Username'),
				'#type' => 'textfield',
				'#size' => 50,
				'#description' => t('Please Enter User Name. User Name Must Be A Unique'),
				// '#description' => t('Spaces are allowed; punctuation is not allowed except for periods, hyphens, and underscores.'),
				'#required' => TRUE,
				);

				$form[ 'loadadmindata' ]['EmailId'] = array(
				'#title' => t('E-mail address'),
				'#type' => 'textfield',
				'#size' => 50,
				'#description' => t('Please Enter Your E-mail Address.Email Address Must Be A Unique'),
				'#required' => TRUE,
				);
				$form[ 'loadadmindata' ]['Password'] = array(
				'#title' => t('Password'),
				'#type' => 'password',
				'#size' => 50,
				'#description' => t('Please Enter Your Password.'),
				'#required' => TRUE,
				);
				$form[ 'loadadmindata' ]['ConfirmPassword'] = array(
				'#title' => t('Confirm password'),
				'#type' => 'password',
				'#size' => 50,
				'#description' => t('Please Confirm Your Password Again.'),
				'#required' => TRUE,
				);
				$form[ 'loadadmindata' ]['MobileNumber'] = array(
				'#title' => t('Mobile Number'),
				'#type' => 'textfield',
				'#size' => 50,
				'#description' => t('Please Enter Your Mobile Number.Mobile Number Must Be A Unique'),
				'#required' => TRUE,
				);
				

				
				$resultg1 = db_query("select * from role where rid in (5,7)");
		
				  $igradeUserOptions = array('' => t('Select..'));

				  while ($rowg1 = db_fetch_object($resultg1)) {

				  	$igradeUserOptions[$rowg1->rid] =  $rowg1->name; //This is the only line that changed from the code above.

				  	}

			

				  $form['loadadmindata']['UserCategory'] = array('#type' => 'select',

				  				  		'#options' => $igradeUserOptions,

				  				  		'#title' => t('User Category'),

				  				  		'#description' => t('Please select the User Category '),

				  				  		'#disabled' => FALSE,
										
										'#required' => TRUE,

                                                                 //     '#prefix' => '<br/><br/><br/><br/><br/><br/><br/>' 


				  );
				
				
				db_set_active('qtxt_db');	

	//  $resultg1 = db_query("SELECT distinct staff_std FROM {qtxt_sms_account_staff}");
	
       $resultg1 = db_query("select distinct standard from {qtxt_sms_account_grades} a , {qtxt_sms_account_staff} b where b.mobile_number = '%s'  and a.account_id = b.account_id  and standard != 'ALL' ", $myMobileNumber );

				  $igradeOptions = array('' => t('Select..'));

				  while ($rowg1 = db_fetch_object($resultg1)) {

				  	$igradeOptions[$rowg1->standard] =  $rowg1->standard; //This is the only line that changed from the code above.

				  	}

				db_set_active('default');

				  $form['loadadmindata']['standard'] = array('#type' => 'select',

				  				  		'#options' => $igradeOptions,

				  				  		'#title' => t('Standard'),

				  				  		'#description' => t('Please select the standard '),

				  				  		'#disabled' => FALSE,

				  );

			
db_set_active('qtxt_db');	

  

	//   $resultg1 = db_query("SELECT distinct staff_section FROM {qtxt_sms_account_staff}");
	
	$resultg1 = db_query("select distinct section from {qtxt_sms_account_grades}  a , {qtxt_sms_account_staff} b where b.mobile_number =  '%s'  and a.account_id = b.account_id  and standard != 'ALL' and section != '' and section != 'ALL' ", $myMobileNumber);
		
				  $igradeSecOptions = array('' => t('Select..'));

				  while ($rowg1 = db_fetch_object($resultg1)) {

				  	$igradeSecOptions[$rowg1->section] =  $rowg1->section; //This is the only line that changed from the code above.

				  	}

				db_set_active('default');

				  $form['loadadmindata']['section'] = array('#type' => 'select',

				  				  		'#options' => $igradeSecOptions,

				  				  		'#title' => t('Section'),

				  				  		'#description' => t('Please select the section '),

				  				  		'#disabled' => FALSE,

				  );


  
	

/*
                  $form['loadadmindata']['usercategory'] = array (
					  '#type' => 'radios', 
					  '#title' => t('Category'), 
					  '#options' => array ( '0' => t('Teacher User'),
                                            '1' => t('Principal User'),
                                         
											),
                  );
*/

			
	$form[ 'loadadmindata' ][ 'submit' ]   = array(
		 '#type' => 'submit',
		'#value' => t( 'Save' ),
		'#prefix' => '<br/>' 
	);
	$form[ 'loadadmindata' ]['submit']['#attributes']['class']  = $form[ 'loadadmindata' ]['submit']['#attributes']['class'] . ' qbsubmit';

	return $form;
}

function v3_load_admindata_main_form_submit( $form, &$form_state ) {
	 global $user;
	 $profile           = profile_load_profile( $user );
	 $myMobileNumber    = $user->profile_mobile;
	// $uid               = $user->uid;
	$staffname         = $form_state[ 'values' ][ 'loadadmindata' ][ 'StaffName' ];
    $username         = $form_state[ 'values' ][ 'loadadmindata' ][ 'UserName' ];
    $emailid         = $form_state[ 'values' ][ 'loadadmindata' ][ 'EmailId' ];
	$pass         = $form_state[ 'values' ][ 'loadadmindata' ][ 'Password' ];
	$encrypt_password=md5($pass);
    $confirmpass         = $form_state[ 'values' ][ 'loadadmindata' ][ 'ConfirmPassword' ];
	$mobilenumber         = $form_state[ 'values' ][ 'loadadmindata' ][ 'MobileNumber' ];
	$usercategory         = $form_state[ 'values' ][ 'loadadmindata' ][ 'UserCategory' ];
    $standard = $form_state['values'][ 'loadadmindata' ][ 'standard' ];
    $section = $form_state['values'][ 'loadadmindata' ][ 'section' ];

	db_set_active( 'default' );
	
	$result = db_query( "INSERT INTO `users`(`uid`,`name`,`pass`,`mail`,`mode`,`sort`,`threshold`,`theme`,`signature`,`signature_format`,`created`,`access`,`login`,`status`,`timezone`,`language`,`picture`,`init`,`data`,`timezone_name`)VALUES(null,'$username','$encrypt_password','$emailid',0,0,0,'','',0,0,0,0,1,-18000,'','','$emailid','','')" );

//	$result = db_query( "INSERT INTO `users_roles` (`uid`,`rid`)VALUES(LAST_INSERT_ID(),$usercategory)");
	
		
	$resultDrpUid = db_query( " select uid from `users` where name = '$username' ");
	$sDrpUid = array( );
	while ( $row = db_fetch_object( $resultDrpUid ) ) {
		$sDrpUid = $row->uid;
	}
	
	$result = db_query( "INSERT INTO `users_roles` (`uid`,`rid`)VALUES($sDrpUid,$usercategory)");

	db_set_active( 'qtxt_db' );
	
	 $result = db_query( "INSERT INTO `qtxt_sms_mobile_numbers`(`mobile_number_id`,`mobile_number`,`preferred_language_id`,`active_flag`,`person_name`,`person_address`,`creation_date`,`last_update_date`,`created_by`,`last_updated_by`,`role_name`,`default_pwd`,`drupal_uid`,`person_email`,`person_home_phone`,`person_relationship_to_student`,`account_notified_flag`,`primary_flag`)VALUES( null,$mobilenumber,1,'Y','$staffname','NULL',sysdate(),sysdate(),'SchoolAdmin','SchoolAdmin','PARENT','$pass',$sDrpUid,'$emailid','NULL','NULL','N','Y')");

	 $resultnMobileNumberId = db_query("select mobile_number_id from `qtxt_sms_mobile_numbers` where mobile_number = $mobilenumber ");

     $nMobileNumberId = array( );
	while ( $row = db_fetch_object( $resultnMobileNumberId ) ) {
		$nMobileNumberId = $row->mobile_number_id;
	}
	
	db_set_active( 'default' );

	$result = db_query( "INSERT INTO `profile_values`(`fid`,`uid`,`value`)VALUES(1,$sDrpUid,'$staffname'),(2,$sDrpUid,'NULL'),(3,$sDrpUid,$mobilenumber),(4,$sDrpUid,'Teacher'),(5,$sDrpUid,'NULL'),(6,$sDrpUid,'NULL'),(7,$sDrpUid,$nMobileNumberId)");

//	 $result = db_query( " SELECT LAST_INSERT_ID() INTO nMobileId ");
	 
db_set_active( 'qtxt_db' );

  $result = db_query( "INSERT INTO `qtxt_sms_account_staff`(`staff_id`,`account_id`,`mobile_number`,`staff_name`,`contact_details`,`staff_std`,`staff_section`,`staff_subject`,`admin_type`,`admin_role`,`created_date`,`last_updated_date`,`created_by`,`last_updated_by`,`staff_email`)VALUES(null,5,$mobilenumber,'$staffname','NULL','$standard','$section','NULL','NULL','NULL',sysdate(),sysdate(),'SchoolAdmin','SchoolAdmin','$emailid')");
  
  $resultnStaffId = db_query("SELECT staff_id from `qtxt_sms_account_staff` where account_id = 5 and mobile_number = $mobilenumber ");
$nStaffId = array( );
	while ( $row = db_fetch_object( $resultnStaffId ) ) {
		$nStaffId = $row->staff_id;
	} 
  
 //  $result = db_query( " SELECT LAST_INSERT_ID() INTO nStaffId ");
  

  $result = db_query ("INSERT INTO `qtxt_sms_admin_mobile` (`admin_mobile_id`,`mobile_number_id`,`staff_id`,`account_id`,`admin_user_id`,`admin_password`,`creation_date`,`last_update_date`,`created_by`,`last_updated_by`,`account_admin_flag`,`driver_admin_flag`) VALUES(null,$nMobileNumberId,$nStaffId,5,'','',sysdate(),sysdate(),'SchoolAdmin','SchoolAdmin','Y','Y')");
 
  $resultnAdminMobileId = db_query( " SELECT admin_mobile_id from `qtxt_sms_admin_mobile` where mobile_number_id = $nMobileNumberId and staff_id = $nStaffId ");
$nAdminMobileId = array( );
	while ( $row = db_fetch_object( $resultnAdminMobileId ) ) {
		$nAdminMobileId = $row->admin_mobile_id;
	}
	 
//	 $result = db_query( " SELECT LAST_INSERT_ID() INTO nAdminMobileId ");
 
     $resultnGradeId = db_query(" SELECT account_grade_id from `qtxt_sms_account_grades` where account_id =  5 and standard = '$standard' and section = '$section' ");
     $nGradeId = array( );
	while ( $row = db_fetch_object( $resultnGradeId ) ) {
		$nGradeId = $row->account_grade_id;
	}

  $result = db_query ("INSERT INTO `qtxt_sms_staff_grade` (`staff_grade_id`,`staff_id`,`account_grade_id`,`creation_date`,`last_update_date`,`created_by`,`last_updated_by`) VALUES (null,$nStaffId,$nGradeId,sysdate(),sysdate(),'SchoolAdmin','SchoolAdmin')");
 
 $resultnStaffGradeId = db_query("SELECT staff_grade_id from `qtxt_sms_staff_grade` where staff_id = $nStaffId  and account_grade_id = $nGradeId ");
 $nStaffGradeId = array( );
	while ( $row = db_fetch_object( $resultnStaffGradeId ) ) {
		$nStaffGradeId = $row->staff_grade_id;
	}
	
 //  $result = db_query( " SELECT LAST_INSERT_ID() INTO nStaffGradeId ");

  	db_set_active( 'default' );
		drupal_set_message(  " User $username Has Been Added Succesfully <br/><br/>");
		drupal_set_message(  " Staff Name : $staffname <br/> ");
		drupal_set_message(  " User Name : $username <br/> ");
		drupal_set_message(  " Password :  $pass <br/>");
				
	return;
}


function v3_load_admindata_main_form_validate( $form, &$form_state ) {


	$values    = $form_state[ 'values' ][ 'loadadmindata' ];
	$staffname     = $values[ 'StaffName' ];
	$username     = $values[ 'UserName' ];
	$emailid   = $values[ 'EmailId' ];
	$pass   = $values[ 'Password' ];
	$confirmpass    = $values[ 'ConfirmPassword' ];
	$mobilenumber       = $values[ 'MobileNumber' ];
	$usercategory       = $values[ 'UserCategory' ];
	$standard     = $values[ 'standard' ];
	$section     = $values[ 'section' ];
	
	$sDrpUid = $row->uid;
	
	 if (!$sDrpUid || ($GLOBALS['user']->uid == $sDrpUid && user_access('change own username')) || user_access('administer users')) {
    if ($error = user_validate_name($values[ 'UserName' ])) {
      form_set_error('name', $error);
    }
    else if (db_result(db_query("SELECT COUNT(*) FROM {users} WHERE uid != %d AND LOWER(name) = LOWER('%s')", $sDrpUid, $values[ 'UserName' ])) > 0) {
      form_set_error('name', t('The username %name is already taken.', array('%name' => $values[ 'UserName' ])));
    }
    else if (drupal_is_denied('user', $values[ 'UserName' ])) {
      form_set_error('name', t('The username %name has been denied access.', array('%name' => $values[ 'UserName' ])));
    }
  }

  // Validate the e-mail address:
  if ($error = user_validate_mail($values[ 'EmailId' ])) {
    form_set_error('mail', $error);
  }
  else if (db_result(db_query("SELECT COUNT(*) FROM {users} WHERE uid != %d AND LOWER(mail) = LOWER('%s')", $sDrpUid, $values[ 'EmailId' ])) > 0) {
    form_set_error('mail', t('The e-mail address %email is already registered.', array('%email' => $values[ 'EmailId' ])));
  }
  else if (drupal_is_denied('mail', $values[ 'EmailId' ])) {
    form_set_error('mail', t('The e-mail address %email has been denied access.', array('%email' => $values[ 'EmailId' ])));
  }

  
  db_set_active( 'qtxt_db' );
 
 if (db_result(db_query("SELECT COUNT(*) FROM {qtxt_sms_mobile_numbers} WHERE mobile_number_id != %d AND LOWER(mobile_number) = LOWER('%d')", $mobilenumber,$values[ 'MobileNumber' ])) > 0) {
  form_set_error('mobile_number', t('The Mobile Number %mobile_number is already registered.', array('%mobile_number' => $values[ 'MobileNumber' ])));
  }
  
 db_set_active( 'default' );	

 
 
	
	$errortxt="";
	
	if ( $pass != $confirmpass ) { $errortxt = $errortxt . "<br/>Enter The Correct Password"; }
	if ( $standard == '' ) { $errortxt = $errortxt . "<br/>Select The Standard"; }
//	if ( $section == '' ) { $errortxt = $errortxt . "<br/>Select The Section"; }

	if ( strlen($errortxt) != 0 )
	{
	//	$errortxt = "<h4>Validation Error - Please review and correct the following.</h4>" . $errortxt; 
		$errortxt = " " . $errortxt; 

		form_set_error( '', t( $errortxt ) );
	}
	
	
}

