<?php

/**

 * Implementation of hook_views_api().

 *

 */

// require ( "../quadroquest/SMSLibrary.php");



function v3_leaveletter_approval_report_parent_views_api() {

  return array(

    'api' => 2,

    'path' => drupal_get_path('module', '  '),

  );

}





function v3_leaveletter_approval_report_parent_menu() {

	$items['report'] = array(

			'title' => t('Leave Letter Reports Sent By Teacher'),

			'page callback' => 'v3_leaveletter_approval_report_parent_form',

			'type' => MENU_CALLBACK,

			'access callback' => 'user_access',

			'access arguments' => array('access content'),

	);

	

	$items['report/next'] = array(

			'title' => t('Are You Sure To Delete The Reports'),

			'page callback' => 'ver3_parent_leaveletter_report_my_form',

			'type' => MENU_CALLBACK,

			'access callback' => 'user_access',

			'access arguments' => array('access content'),

	);	

	

	return $items;

}



	

function v3_leaveletter_approval_report_parent_form() {

			$output = drupal_get_form('v3_leaveletter_approval_report_parent_filter_form');

			 $output .= drupal_get_form('v3_leaveletter_approval_report_parent_my_form');

			return $output ;

          }

		  

		  function v3_leaveletter_approval_report_parent_filter_form($form_state) {

global $user;

$profile =  profile_load_profile($user);

$myMobileNumber =  $user->profile_mobile; 

$uid = $user->uid;

$c2Val;



		if(!empty($_SESSION['user_class_filter_value'])) {

			$clVal = &$_SESSION['user_class_filter_value'];

		} else {

			$clVal = "";

		}

		if(!empty($_SESSION['user_section_filter_value'])) {

			$c2Val = &$_SESSION['user_section_filter_value'];

		} else {

			$c2Val = "";

		}



	$_SESSION['user_class_filter_value'] = $clVal;

	$_SESSION['user_section_filter_value'] = $c2Val;







 $i = 0;

  $form['filters'] = array(

    '#type' => 'fieldset',

    '#title' => t('Filter'),

  //  '#theme' => 'user_filters',

  );



  

db_set_active('qtxt_db');	



$result = db_query("select distinct account_student_map_id,student_name from {qtxt_sms_mobile_students_v} where drupal_uid =  $uid");

 $options = array('' => t('Select..'));

while ($row = db_fetch_object($result)) {

  $options[$row->account_student_map_id ] =  $row->student_name; 

  // This is the only line that changed from the code above.

}

 db_set_active('default');

  

  $form['filters']['class'] = array(

      '#title' => t('Student Name'),

	  '#type' => 'select',
// '#type' => 'hidden',
 '#description' => t('Please Select The Student Name'),
      '#options' => $options,

    );

	

	

$form['filters']['class']['#default_value']	= $clVal;

// $form['filters']['section']['#default_value'] = $c2Val;  



/*

 $form['filters']['buttons']['submit'] = array(

    '#type' => 'submit',

    '#value' => t('Apply'),

  );

return $form;



*/

 $form['filters']['buttons']['submit'] = array(

    '#type' => 'submit',

    '#value' => t('Apply'),

    '#prefix' => '<br/>',

  );
$form['filters']['buttons']['submit']['#attributes']['class']  = $form['filters']['buttons']['submit']['#attributes']['class'] . ' qbsubmit';

return $form;



}

function v3_leaveletter_approval_report_parent_filter_form_submit($form, &$form_state) {

global $user;

$profile =  profile_load_profile($user);

$myMobileNumber =  $user->profile_mobile; 

$uid = $user->uid;



  $op = $form_state['values']['op'];


  switch ($op) {

   case t('Apply'): 



      

	   if (isset($form_state['values']['class'])) {

			$filter = $form_state['values']['class'];

		 

			$_SESSION['user_class_filter_value'] = $form_state['values']['class'];

      } else  {

		  $_SESSION['user_class_filter_value'] = "";	

		  unset ( $_SESSION['user_class_filter_value'] );

		  

	  }


	  break;

    case t('Undo'):

//      array_pop($_SESSION['user_overview_filter']);

      break;

    case t('Reset'):

//      $_SESSION['user_overview_filter'] = array();

      break;

    case t('Delete'):

      return;

  }

//	drupal_set_message(t(" Selected Approval Report has been Deleted Successfully "));



  $form_state['redirect'] = 'report';

  return;

}

function v3_leaveletter_approval_report_parent_my_form($form_state) {

global $user; 

$profile =  profile_load_profile($user);

$myMobileNumber =  $user->profile_mobile; 

$uid = $user->uid;



  $header = array(

    array(),

    array('data' => t('Student Name'), 'field' => 'student_name'),

    array('data' => t('Teacher Name'), 'field' => 'teacher_name'),

    array('data' => t('Message'), 'field' => 'message'),

    array('data' => t('Delivery Report'), 'field' => 'delivery_report'),

    array('data' => t('Reason'), 'field' => 'comments'),

  //  array('data' => t('Student Name'), 'field' => 'student_name'),
	 

	

  );



$clVal = &$_SESSION['user_class_filter_value'] ;

// $c2Val = &$_SESSION['user_section_filter_value'] ;





$filterClass = "";





	 if  ( ( ! isset($clVal) )|| ( $clVal == "" ) ) {

			$accountArray = "";

		db_set_active('qtxt_db');	



		$result = db_query("select account_student_map_id from {qtxt_sms_mobile_students_v} where drupal_uid = $uid ");



		$accountGradeId = array();



		while ($row = db_fetch_object($result)) {



		  $accountGradeId[] =  $row->account_student_map_id; 

		  // This is the only line that changed from the code above.

		}

		db_set_active('default');

		

		if (  count( $accountGradeId ) > 0 ) {

			$accountArray = join( ",", $accountGradeId );

		}

		$filterClass = " and account_student_map_id in (" . $accountArray . " ) ";
// drupal_set_message(t("Map $filterClass")); 

	} else {

		$filterClass = " and account_student_map_id = '$clVal' ";

	}


  db_set_active('qtxt_db');	

  

 

 $sql = "select distinct(student_name),teacher_name,message,delivery_report,comments,parent_message_id,str_msg_creation_date from {qtxt_sms_parent_messages_report_v3} where ((process_flag = 0) or (process_flag = 1)) and drupal_uid = $uid and type_id = 4 " . $filterClass . "order by parent_message_id desc"; 



 $query_count = "select count(parent_message_id) from {qtxt_sms_parent_messages_report_v3} where (( process_flag = 0) or (process_flag = 1)) and drupal_uid = $uid and type_id =4 " . $filterClass . "order by parent_message_id desc" ; 






$sql .= tablesort_sql($header);



       $result = pager_query($sql, 5000, 0, $query_count);


  $form['options'] = array(

    '#type' => 'fieldset',

    '#title' => t('Delete The Approval Report'),

     '#suffix' => '</div>',

  );

  

  $form['options']['submit'] = array(

    '#type' => 'submit',

    '#value' => t('Delete'),

  );





    $form['access'] = array(

    '#type' => 'fieldset',

    '#title' => t('Access log settings'),

    '#tree' => TRUE,

	'#visible' => false,

  );  



  $account = array();



$i = 1;  

  while ($account = db_fetch_object($result)) {

	$form['access']['account'][$i] = array(

		'#type' => 'checkbox',

		'#return_value' => $account->parent_message_id,

		'#default_value' => 0,

		'#tree' => TRUE,



	  );
 $form['access']['studentname'][$account->parent_message_id] = array('#value' => $account->student_name);

    $form['access']['teachername'][$account->parent_message_id] =  array('#value' => $account->teacher_name);

    $form['access']['message'][$account->parent_message_id] =  array('#value' => $account->message);

    $form['access']['deliveryreport'][$account->parent_message_id] =  array('#value' => $account->delivery_report);

    $form['access']['comment'][$account->parent_message_id] =  array('#value' => $account->comments);

$form['access']['msgcreationdate'][$account->parent_message_id] = array('#value' => $account->str_msg_creation_date);

   
    $form['access']['accountgradeid'][$account->parent_message_id] =  array('#type' => 'hidden','#value' => $account->parent_message_id);

	

	$i = $i + 1;

  }

db_set_active('default');



  // $form['pager'] = array('#value' => theme('pager', NULL, 5000, 0));

  $form['#theme'] = 'v3_leaveletter_approval_report_parent_my_form_theme';   

  $form['totalcount'] = array(

	'#type' => 'hidden', '#default_value' => ($i  -10 )

  );  

  return $form;

}



function v3_leaveletter_approval_report_parent_theme() {

	return array(

		'v3_leaveletter_approval_report_parent_my_form_theme' => array('arguments'=> array('form' => NULL),),

		'v3_leaveletter_approval_report_parent_my_next_form_theme' => array('arguments'=> array('form' => NULL),),

	);

}

function v3_leaveletter_approval_report_parent_my_form_submit($form, &$form_state) {





	$TotalCount = $form_state['values']['totalcount'];

	

	$myArray = array();

	

	if ( isset( $form_state['clicked_button']['#post']['access']['account'] ) ) 

	{

	$myArray = $form_state['clicked_button']['#post']['access']['account'];

	

	}

	foreach ($myArray as $key => $value) {

	}

	$_SESSION['user_total_count'] =  $TotalCount;

	$_SESSION['selectOptions'] =  $myArray;

	$selList = &$_SESSION['selectOptions'];

	

	foreach ($selList as $key => $value) {



	db_set_active('qtxt_db');



	

  $sql = db_query("Update qtxt_sms_parent_message set process_flag = 2  where parent_message_id = $value ") ; 





	}

	drupal_set_message(t(" Selected Approval Report has been Deleted Successfully. "));

	

	$form_state['redirect'] =   'report';

	

  return;	 
  
}



function theme_v3_leaveletter_approval_report_parent_my_form_theme($form)

{

$rows = array();

$i = 1;

foreach(element_children($form['access']['accountgradeid']) as $key) {

	$row = array(); 

       $row[] =  drupal_render($form['access']['account'][$i]);

$row[] =  drupal_render($form['access']['msgcreationdate'][$key]);

$row[] =  drupal_render($form['access']['studentname'][$key]);
  
$row[] =  drupal_render($form['access']['teachername'][$key]);

$row[] =  drupal_render($form['access']['message'][$key]);

$row[] =  drupal_render($form['access']['deliveryreport'][$key]);

$row[] =  drupal_render($form['access']['comment'][$key]);


	 // $row[] =  drupal_render($form['access']['accountgradeid'][$key]);

	   $rows[] = $row; 

	$i = $i +1 ;

}



if(count($rows)){

			$header = array(

				theme('table_select_header_cell') ,t('Created On'),t('Student'), t('Staff'), t('Message'), 

				 t('Status'), t('Comments'));


  }

  else{

    $header = array(t(''), t('')); 

    $row = array();

    $row[] = array

    (

      'data' => t('No Data Found for the Selected Criteria'),

      'colspan' => 2,

      'style' => 'text-align:center'

    );

    $rows[] = $row;

  }

$output = theme('table', $header, $rows); 

//return $output . drupal_render($form); 

 $form['access']['#access'] = false;

 return $output . drupal_render($form); 

 return $output ;

}



// v3_leaveletter_approval_report_parent_filter_form 
 function v3_leaveletter_approval_report_parent_my_form_validate($form, &$form_state) {

// function v3_leaveletter_approval_report_parent_filter_form_validate($form, &$form_state) {



	if ( !isset( $form_state['clicked_button']['#post']['access']['account'] ) ) 

	{

	form_set_error('', t('Please Select At Least One Approval Report To Be Delete'));

	

	}

		
}







		 