<?php

/**

 * Implementation of hook_views_api().

 *

 */

// require ( "../quadroquest/svrs/QtxtSVRSLibrary.php");



function v3_coscholastic_marks_info_views_api() {

  return array(

    'api' => 2,

    'path' => drupal_get_path('module', 'v3_coscholastic_marks_info'),

  );

}



function v3_coscholastic_marks_info_menu() {

	$items['coscholasticmarks'] = array(

			'title' => t('Co Scholastic Marks Details'),

			'page callback' => 'v3_coscholastic_marks_info_form',

			'type' => MENU_CALLBACK,

			'access callback' => 'user_access',

			'access arguments' => array('access content'),

	);

	

	

	return $items;

	

	}

	
 function v3_coscholastic_marks_info_form() {

			$output = drupal_get_form('v3_coscholastic_marks_filter_form');

			 $output .= drupal_get_form('v3_coscholastic_marks_my_form');

			return $output ;

} 
function v3_coscholastic_marks_filter_form() {

			
	 $i = 0;
	  $form['filters'] = array(
		'#type' => 'fieldset',
		'#title' => t('Show only Grade,Student Name,Assessment Name where'),

	  );		

		
		$c3Val = "";
		$c4Val = "";
		$c5Val = "";		
		
		
		if(!empty($_SESSION['section_filter_value'])) {
			$c3Val = &$_SESSION['section_filter_value'];
		} else {
			$c3Val = "";
		}
		if(!empty($_SESSION['section1_filter_value'])) {
			$c4Val = &$_SESSION['section1_filter_value'];
		} else {
			$c4Val = "";
		}
		if(!empty($_SESSION['section2_filter_value'])) {
			$c5Val = &$_SESSION['section2_filter_value'];
		} else {
			$c5Val = "";
		}
		
		
		
		db_set_active('qtxt_db');	
		$result = db_query("select distinct( assessment_name)  from {cce_coschol_marks_details_v} a  " );

$sectionoptions = array('' => t('Select..'));

while ($row = db_fetch_object($result)) {
  $sectionoptions[$row->assessment_name] =  $row->assessment_name; //This is the only line that changed from the code above.
}
db_set_active('default');

$key = 'section';				
 $names[$key] = 'Type ';
 $form['filters']['status'][$key] = array(
      '#type' => 'select',
	  '#title' => 'Assessment Name ',
      '#options' => $sectionoptions,
    );
	
	db_set_active('qtxt_db');	
		$result = db_query("select  distinct(grade_name)  from {cce_coschol_marks_details_v} a  " );

$sectionoptions1 = array('' => t('Select..'));

while ($row = db_fetch_object($result)) {
  $sectionoptions1[$row->grade_name ] =  $row->grade_name; //This is the only line that changed from the code above.
}
db_set_active('default');

$key = 'section1';				
 $names[$key] = 'Type ';
 
 $form['filters']['status'][$key] = array(
      '#type' => 'select',
	  '#title' => 'Grade Name',
      '#options' => $sectionoptions1,
    );
	db_set_active('qtxt_db');	
		$result = db_query("select  distinct(account_student_map_id), student_name  from {cce_coschol_marks_details_v} a  " );

$sectionoptions2 = array('' => t('Select..'));

while ($row = db_fetch_object($result)) {
  $sectionoptions2[$row->account_student_map_id ] =  $row->student_name; //This is the only line that changed from the code above.
}
db_set_active('default');

$key = 'section2';				
 $names[$key] = 'Type ';

 $form['filters']['status'][$key] = array(
      '#type' => 'select',
	   '#title' => 'Student Name',
      '#options' => $sectionoptions2,
	  );

	 $form['filters']['buttons']['submit'] = array(                                                          
		'#type' => 'submit',
		'#value' => t('Filter'),                                                 
	  );

	return $form;

}
function v3_coscholastic_marks_filter_form_submit($form, &$form_state) {
  $op = $form_state['values']['op'];
//  drupal_set_message("Filter Form Submit Operamd - $op ");	  
  switch ($op) {
    case t('Filter'): 


       if (isset($form_state['values']['section'])) {
			// drupal_set_message(t("In the Filter, Class  selected"));	 	  
			$filter = $form_state['values']['section'];
			// drupal_set_message(t("In the Filter, Class  $filter"));	 	  
			
			$_SESSION['section_filter_value'] = $form_state['values']['section'];
	  }
	   if (isset($form_state['values']['section1'])) {
			// drupal_set_message(t("In the Filter, Class  selected"));	 	  
			$filter = $form_state['values']['section1'];
			// drupal_set_message(t("In the Filter, Class  selected $filter"));	 	  
			
			$_SESSION['section1_filter_value'] = $form_state['values']['section1'];
	  }
	   if (isset($form_state['values']['section2'])) {
			// drupal_set_message(t("In the Filter, Class  selected"));	 	  
			$filter = $form_state['values']['section2'];
			// drupal_set_message(t("In the Filter, Class  selected - $filter"));	 	  
			
			$_SESSION['section2_filter_value'] = $form_state['values']['section2'];
	  }
	 
	 
	 
	  
      break;
  }
  
  $form_state['redirect'] = 'coscholasticmarks';
  return;
}




function v3_coscholastic_marks_my_form($form_state) {
global $user;
$profile =  profile_load_profile($user);
$myMobileNumber =  $user->profile_mobile; 
$uid = $user->uid;
$c2Val = &$_SESSION['section_filter_value'] ;
 // drupal_set_message(t("Class Filter 1 - $c2Val"));	
$c3Val = &$_SESSION['section1_filter_value'] ;
// drupal_set_message(t("Class Filter 1 - $c3Val"));	
$c4Val = &$_SESSION['section2_filter_value'] ;
 // drupal_set_message(t("Class Filter 1 - $c4Val"));	


$filterClass1 = "";
	if ( $c2Val != "" ) {
					$filterClass1 = " and b.assessment_name  = '$c2Val' ";
					 // drupal_set_message(t("Class1 - $filterClass1"));
	} else {
			$filterClass1 = " and  b.assessment_name = b.assessment_name ";
 // drupal_set_message(t("Class1 - $filterClass1"));

	}
	$filterClass2 = "";
	if ( $c3Val != "" ) {
		
			$filterClass2 = " and b.grade_name = '$c3Val' ";
			//  drupal_set_message(t("Class1 - $filterClass2"));
	} else {
			$filterClass2 = " and b.grade_name = b.grade_name ";
 // drupal_set_message(t("Class1 - $filterClass2"));

	}
	$filterClass3 = "";
	if ( $c4Val != "" ) {
			$filterClass3 = " and b.account_student_map_id= $c4Val ";
			//  drupal_set_message(t("Class1 - $filterClass3"));
	} else {
			$filterClass3 = " and b.account_student_map_id = b.account_student_map_id ";
 // drupal_set_message(t("Class1 - $filterClass3"));

	}
	






  $header = array(
    array(),
    array('data' => t('aname'), 'field' => 'b.assessment_name,'),
    array('data' => t('acode'), 'field' => 'b.assessment_category_code'),
    array('data' => t('actype'), 'field' => 'b.assessment_category_type'),
    array('data' => t('sname'), 'field' => 'b.student_name'),
	array('data' => t('gname'), 'field' => 'b.grade_name'),
	array('data' => t('mobtained'), 'field' => 'marks_obtained'),
	array('data' => t('max marks'), 'field' => 'b.max_marks'),
	// array('data' => t('subject'), 'field' => 'b.SUBJECT_NAME'),
	
  );



// drupal_set_message(t("Class Filter, $filterClass"));	

  db_set_active('qtxt_db');	
   
 	$sql = "select b.assessment_name,
b.assessment_category_code,
     b.assessment_category_type,
     b.student_name,
	 b.grade_name,
	 b. marks_obtained,
	 b.max_marks,
	 b.mark_details_id,
	b.SUBJECT_NAME from 
	{cce_coschol_marks_details_v} b where 1=1 " . $filterClass1 . $filterClass2 . $filterClass3 ;

     $query_count = "select count(b.mark_details_id) from {cce_coschol_marks_details_v} b where 1 = 1 " . $filterClass1 . $filterClass2 . $filterClass3;
	 
	 	 
   
	 $sql .= tablesort_sql($header);

   $result = pager_query($sql, 10, 0, $query_count);

   
/*
    $form['access'] = array(
    '#type' => 'fieldset',
    '#title' => t('Access log settings'),
    '#tree' => TRUE,
	'#visible' => false,
  );  
*/
  $account = array();

$i = 1;  
  while ($account = db_fetch_object($result)) {
	$form['access']['account'][$i] = array(
		// '#type' => 'checkbox',
		'#return_value' => $account->mark_details_id,
		'#default_value' => 0,
		'#tree' => TRUE,
		'#disabled'=>True,
		

	  );
	$form['access']['aname'][$account->mark_details_id] = array('#value' => $account->assessment_name);
    $form['access']['acode'][$account->mark_details_id] =  array('#value' => $account->assessment_category_code);
    $form['access']['actype'][$account->mark_details_id] =  array('#value' => $account->assessment_category_type);
	$form['access']['sname'][$account->mark_details_id] =  array('#value' => $account->student_name);
    $form['access']['gname'][$account->mark_details_id] =  array('#value' => $account->grade_name);
	 $form['access']['marks'][$account->mark_details_id] =  array('#value' => $account->marks_obtained);
	 //  $form['access']['subject'][$account->mark_details_id] =  array('#value' => $account->SUBJECT_NAME);
	  $form['access']['maxmarks'][$account->mark_details_id] =  array('#value' => $account->max_marks);
	  
	  $form['access']['studentid'][$account->mark_details_id] =  array('#value' => $account->mark_details_id);
	  
	
	$i = $i + 1;
  }
db_set_active('default');

  $form['pager'] = array('#value' => theme('pager', NULL, 10, 0));
  $form['#theme'] = 'v3_coscholastic_marks_my_form_theme';   
  $form['totalcount'] = array(
	'#type' => 'hidden', '#default_value' => ($i  -1 )
  );  
  return $form;

}  

  function v3_coscholastic_marks_info_theme() {
	return array(
		'v3_coscholastic_marks_my_form_theme' => array('arguments'=> array('form' => NULL),),
		// 'v3_academic_my_form_theme' => array('arguments'=> array('form' => NULL),),
	);
}

function theme_v3_coscholastic_marks_my_form_theme($form)
{
$rows = array();
$i = 1;
foreach(element_children($form['access']['studentid']) as $key) {
	$row = array(); 
       // $row[] =  drupal_render($form['access']['account'][$i]);
	   $row[] =  drupal_render($form['access']['aname'][$key]);
       $row[] =  drupal_render($form['access']['acode'][$key]);
       $row[] =  drupal_render($form['access']['actype'][$key]);
       $row[] =  drupal_render($form['access']['sname'][$key]);
        // $row[] =  drupal_render($form['access']['subject'][$key]);	
	   $row[] =  drupal_render($form['access']['gname'][$key]);
	   $row[] =  drupal_render($form['access']['marks'][$key]);
	  $row[] =  drupal_render($form['access']['maxmarks'][$key]);
	  $row[] =  drupal_render($form['access']['studentid'][$key]);
	  
	  
	   $row[] =  drupal_render($form['access']['studentid'][$key]);
	  
	  
	   $rows[] = $row; 
	$i = $i +1 ;
}

if(count($rows)){
			  $header = array(('Assessment  Name'), t('Assessment Code'),  t('Assessment Category type'),
				t('Student Name'),t('Grade Name'),t('Marks Obtained'),t('Max Marks'),t('Id'));
  }
  else{
    $header = array(t(''), t('')); 
    $row = array();
    $row[] = array
    (
      'data' => t('Filter the Students to set the Info'),
      'colspan' => 2,
      'style' => 'text-align:center'
    );
    $rows[] = $row;
  }
$output = theme('table', $header, $rows); 
return $output . drupal_render($form); 
}  






