<?php
/**
 * Implementation of hook_views_api().
 *
 */
// require ( "../quadroquest/SMSLibrary.php");
//require ( "cceClass.php");

function v3_cce_fileupload_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'v3_cce_fileupload'),
  );
}



function v3_cce_fileupload_menu() {
	$items['ccefileupload'] = array(
			'title' => t('CCE File Upload  - Welcome Screen'),
			'page callback' => 'v3_cce_fileupload_form_wrap',
			'type' => MENU_CALLBACK,
			'access callback' => 'user_access',
			'access arguments' => array('access content'),
	);
	$items['ccefileupload/next'] = array(
			'title' => t('Online Messages to Parents  - Next Screen'),
			'page callback' => 'v3_cce_fileupload_next_form_wrap',
			'type' => MENU_CALLBACK,
			'access callback' => 'user_access',
			'access arguments' => array('access content'),
	);

 $items['fileupload/group/ahahjs0'] = array(
        'page callback' => 'ahah_terms_for_group',
        'type' => MENU_CALLBACK,
		'access callback' => 'user_access',
		'access arguments' => array('access content'),	
  );
/*	  
 $items['fileupload/term/ahahjs0'] = array(
        'page callback' => 'fileupload_ahah_access_for_terms',
        'type' => MENU_CALLBACK,
		'access callback' => 'user_access',
		'access arguments' => array('access content'),	
  );
	 
 $items['fileupload/assessname/ahahjs1'] = array(
        'page callback' => 'fileupload_ahah_accesscat_for_access',
        'type' => MENU_CALLBACK,
		'access callback' => 'user_access',
		'access arguments' => array('access content'),	
  );
	 	
		
 $items['fileupload/assesscat/ahahjs2'] = array(
        'page callback' => 'fileupload_ahah_accesscatdet_for_accesscat',
        'type' => MENU_CALLBACK,
		'access callback' => 'user_access',
		'access arguments' => array('access content'),	
  );
*/	 	
		
		
return $items;
}

function v3_cce_fileupload_form_wrap() {
			$output = drupal_get_form('v3_cce_fileupload_form');
			return $output ;
}

function v3_cce_fileupload_next_form_wrap() {
			$output = drupal_get_form('v3_cce_fileupload_next_form');
			return $output ;
}



 
function v3_cce_fileupload_form( $form_state) {

global $user;
//$profile =  profile_load_profile($user);
//$myMobileNumber =  $user->profile_mobile;  

//$defusermobile = $myMobileNumber;
$defadminuserid = "";
$defadminpwd = "";

	  db_set_active('qtxt_db');	

	  
	  $resultg1 = db_query("select account_id, account_name from {qtxt_sms_account} WHERE party_id = 5 ");
				  $igradeOptions = array();
				  while ($rowg1 = db_fetch_object($resultg1)) {
				  	$igradeOptions[$rowg1->account_id ] =  $rowg1->account_name; //This is the only line that changed from the code above.
				  	}
	db_set_active('default');
				  $form['institution'] = array('#type' => 'select',
				  				  		'#options' => $igradeOptions,
				  				  		'#title' => t('Institution'),
				  				  		'#description' => t('Please select the Institution '),
				  				  		'#disabled' => FALSE,
				  );
				  


		db_set_active('qtxt_db');	
		$result1 = db_query("SELECT group_id, concat( group_name , ' - ' , group_description ) 'groupdesc' FROM {cce_groups} a ");
		$accessOptions = array( '' => t('Select the Group Name') );
		while ($row = db_fetch_object($result1)){
		  $accessOptions[$row->group_id ] = $row->groupdesc; 
		}
		db_set_active('default');	

		
		$form['groupid'] = array(
			'#type' => 'select',
			'#description' => t('Please select the Group Name'),
			'#options'=> $accessOptions,
			'#title' => t('Group'),
			'#disabled' => FALSE,
		
		);

		
		db_set_active('qtxt_db');	
		$result1 = db_query("SELECT account_grade_id, grade_name FROM {cce_qtxt_sms_account_grades_v} a ");
		$accessOptions = array( '' => t('Select the Grade Name') );
		while ($row = db_fetch_object($result1)){
		  $accessOptions[$row->account_grade_id ] = $row->grade_name; 
		}
		db_set_active('default');			

		
		$form['class'] = array(
			'#type' => 'select',
			'#description' => t('Please select the Class Name'),
			'#options'=> $accessOptions,
			'#title' => t('Class'),
			'#disabled' => FALSE,
	
		);


		db_set_active('qtxt_db');	
		$result1 = db_query("SELECT subject_id, subject_name  FROM {qtxt_sms_subjects} a ");
		$accessOptions1 = array( '' => t('Select the Subject') );
		while ($row = db_fetch_object($result1)){
		  $accessOptions1[$row->subject_id ] = $row->subject_name; 
		}
		db_set_active('default');	
		
		$form['subject'] = array(
			'#type' => 'select',
			'#description' => t('Please select the Subject'),
			'#options'=> $accessOptions1,
			'#title' => t('Subject'),
			'#disabled' => FALSE,
		);		
		
		



			
			
			

		db_set_active('qtxt_db');	
		$result1 = db_query("SELECT assessment_id, concat( term_id, '-', group_id , '-', assessment_name) 'assessment_name' FROM {cce_assesment_types} a ");
		$accessOptions = array( '' => t('Select the Assessment Name') );
		while ($row = db_fetch_object($result1)){
		  $accessOptions[$row->assessment_id ] = $row->assessment_name; 
		}
		db_set_active('default');			
		$form['assessname'] = array(
			'#type' => 'select',
			'#description' => t('Please select the Assessment Name'),
			'#options'=> $accessOptions,
			'#title' => t('Assessment Name'),
			'#disabled' => FALSE,
		);
					
					

		db_set_active('qtxt_db');	
		$result1 = db_query("select  concat( assessment_id, '-', assessment_category_type) 'categ_type',    assessment_category_detail_id from {cce_assesment_category_details_v} b   ");
		$accessOptions = array( '' => t('Select the Category Name') );
		while ($row = db_fetch_object($result1)){
		  $accessOptions[$row->assessment_category_detail_id ] = $row->categ_type; 
		}
		db_set_active('default');	
		$form['assesscatdetlist'] = array(
			'#type' => 'select',
			'#description' => t('Please select the Category'),
			'#options'=> $accessOptions,
			'#title' => t('Category Detail'),
			'#disabled' => FALSE,
		);


		$form['assesscatdescriptors'] = array(
			'#type' => 'select',
			'#description' => t('Please select the Descriptor'),
			'#options'=> array( '' => t('Select ..') ),
			'#title' => t('Category Detail'),
			'#disabled' => FALSE,
			 '#prefix' => '<div id = "ahah-wrapper-defaultlist">',
				'#suffix' => '</div>',	
		);					

	  $form['#attributes']['enctype'] = "multipart/form-data";
		db_set_active('qtxt_db');		  
	  $resultg1 = db_query("select template_id, template_name from {qtxt_sms_template_master} where tag = 'cce'");
				  $igradeOptions2 = array();
				  while ($rowg1 = db_fetch_object($resultg1)) {
				  	$igradeOptions2[$rowg1->template_id ] =  $rowg1->template_name; //This is the only line that changed from the code above.
				  	}
				db_set_active('default');				  
				  
				  $form['interfaceType'] = array('#type' => 'select',
				  				  		'#title' => t('Interface Type'),
										'#options' =>  $igradeOptions2,
				  				  		'#description' => t('Please select the Template'),
				  				  		'#disabled' => FALSE,
				  );
				  
				  $form['tcsv'] = array('#type' => 'file',
				  				  		'#title' => t('Upload File'),
				  				  		'#description' => t('Pick a file to upload'),
				  );
				  

			  $form['submit'] = array(
				'#type' => 'submit',
				'#value' => t('Confirm'),
			  );
			return $form;
 
}



function v3_cce_fileupload_form_submit($form, &$form_state) {
	global $user;
//	$profile =  profile_load_profile($user);
//	$myMobileNumber =  $user->profile_mobile; 
//	$uid = $user->uid;
//	$_SESSION['t_student'] = $form_state['values']['institution'];
//	$_SESSION['t_student_grade'] = $form_state['values']['adminOuter']['grade'];

	$dir = file_directory_path();

		if(isset($_FILES) && !empty($_FILES) && $_FILES['files']['size']['tcsv'] != 0){
		
			#this structure is kind of wacky
			$name = $_FILES['files']['name']['tcsv'];
			$size = $_FILES['files']['size']['tcsv'];
			$type = $_FILES['files']['type']['tcsv'];

			#this is the actual place where we store the file
			$file = file_save_upload('tcsv', array() , $dir);

		} 	
		
	$_SESSION['ccefilename'] = $name;
	$_SESSION['ccedir'] = $dir;
	$_SESSION['cceaccount'] = $form_state['values']['institution'];
	$_SESSION['t_interface_type'] = $form_state['values']['interfaceType'];	
	$_SESSION['cceassessment'] = $form_state['values']['assessment'];
	
	$form_state['redirect'] = 'ccefileupload/next';
  return;

}

function v3_cce_fileupload_next_form ($form_state) {

	return $form;
	
}






function ahah_terms_for_group() {

		$form_state = array('storage' => NULL, 'submitted' => FALSE);
		$form_build_id = $_POST['form_build_id'];

		// Get for the form from the cache
		$form = form_get_cache($form_build_id, $form_state);
  
		// Get the form set up to process
		$args = $form['#parameters'];
		$form_id = array_shift($args);
		$form_state['post'] = $form['#post'] = $_POST;
		$msgId = $form['#post']['groupid'];

		db_set_active('qtxt_db');

		$sqlg = "select  account_grade_id, grade_name  from cce_qtxt_sms_account_grades_v b  where group_id = $msgId";

        $resultg = db_query($sqlg);
		$valueg[''] = 'Select a Value+++..';
		while($datag = db_fetch_object($resultg))
		{
		$valueg[$datag->account_grade_id] = $datag->grade_name;
		}
		db_set_active('default');

		$form['class1']['#options'] = $valueg;
		form_set_cache($form_build_id, $form, $form_state);
				$form += array(
					'#post' => $_POST,
					'#programmed' => FALSE,
				  );
	
           $form = form_builder('form_details', $form, $form_state);			
				$output = $form['class1'];
				unset($output['#prefix'],$output['#suffix']);
				$out1 =  drupal_render($output);
				drupal_json(array('status' => TRUE, 'data' => $out1));

}


/*

$form_state = array('storage' => NULL, 'submitted' => FALSE);
		$form_build_id = $_POST['form_build_id'];

		// Get for the form from the cache
		$form = form_get_cache($form_build_id, $form_state);
  
		// Get the form set up to process
		$args = $form['#parameters'];
		$form_id = array_shift($args);
		$form_state['post'] = $form['#post'] = $_POST;
		$gid = $form['#post']['groupid'];
//		db_set_active('qtxt_db');

		db_set_active('qtxt_db');

		$sqlg = "select  b.account_grade_id, b.grade_name  from cce_qtxt_sms_account_grades_v b  where group_id = $gid ";

        $resultg = db_query($sqlg);
		$valueg[''] = 'Select a Value++.. ';
		while($datag = db_fetch_object($resultg))
		{
		$valueg[$datag->account_grade_id] = $datag->grade_name;
		}
		db_set_active('default');
		
		
		$form['class']['#options'] = $valueg;
							
		
		form_set_cache($form_build_id, $form, $form_state);
				$form += array(
					'#post' => $_POST,
					'#programmed' => FALSE,
				  );
	
           $form = form_builder('form_details', $form, $form_state);			
				$output = $form['class'];
				unset($output['#prefix'],$output['#suffix']);
				$out1 =  drupal_render($output);
				drupal_json(array('status' => TRUE, 'data' => $out1));

}
*/
