<?php
function v3_cce_assesstype_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'v3_cce_assesstype'),
  );
}
function v3_cce_assesstype_help($path, $arg) {
  global $user;

  switch ($path) {
    case 'assesstype':
      return '<p>'. t('Define an assessment types for the assesment category type which we have already defined') .'</p>';
	
	}
  
}  
function v3_cce_assesstype_menu() {
	$items['assesstype'] = array(
    'title' => 'CCE - Define Assessment Category Type',
    'description' => 'List, add, and edit assesstype.',
    'page callback' => 'cce_assesstype',
    'page arguments' => array('list'),
    // 'access arguments' => array('administer users'),
	'type' => MENU_CALLBACK,	
'access callback' => 'user_access',
'access arguments' => array('access content'),

	);

  $items['assesstype/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
'access callback' => 'user_access',
'access arguments' => array('access content'),


    'weight' => -10,
  );
  $items['assesstype/create'] = array(
    'title' => 'Add Assessment Category Type',
    'page arguments' => array('create'),
   // 'access arguments' => array('administer users'),
    'type' => MENU_LOCAL_TASK,
'access callback' => 'user_access',
'access arguments' => array('access content'),


  );	
  $items['assesstype/group/ahahjs0'] = array(
        'page callback' => 'assesstype_ahah_for_group',
        'type' => MENU_CALLBACK,
		'access callback' => 'user_access',
		'access arguments' => array('access content'),	
  );

  
  $items['assesstype/edit'] = array(
    'title' => 'Edit Assessment Category Type',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('assesstype_edit'),
   // 'access arguments' => array('administer users'),
    'type' => MENU_CALLBACK,
'access callback' => 'user_access',
'access arguments' => array('access content'),


  );
  $items['assesstype/delete'] = array(
    'title' => 'Delete Assessment Category Type',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('assesstype_delete'),
  //  'access arguments' => array('administer users'),
    'type' => MENU_CALLBACK,
'access callback' => 'user_access',
'access arguments' => array('access content'),


  );  
	
 $items['assesstype/year/ahahjs2'] = array(
        'page callback' => 'ahah_for_assterm_to_derive_defaultvalues',
        'type' => MENU_CALLBACK,
		'access callback' => 'user_access',
		'access arguments' => array('access content'),	
  );
	  
  
return $items;
}

function assesstype_edit(&$form_state, $fid) {
		db_set_active('qtxt_db');
		$field = db_fetch_object(db_query("SELECT assessment_category_type, assessment_description 
		FROM {cce_assesment_category_details} WHERE assessment_category_detail_id = %d", $fid));
		db_set_active('default');

		if (!$field) {
			drupal_not_found();
			return;
		  }
		  $form['assessment_category_detail_id'] = array('#type' => 'value',
			'#value' => $fid,
		  );		  



		$form['userdefinedvalue'] = array(
			'#type' => 'textfield',
			'#description' => t('Please enter your own assessment category types'),
			'#title' => t('Assessment Category Type'),
			  '#size' => 60,
			  '#maxlength' => 500,	
			'#default_value' => $field->assessment_category_type,
		);			
			

		$form['userdefineddesc'] = array(
			'#type' => 'textfield',
			'#description' => t('Please enter assessment category type description'),
			'#title' => t('Assessment Category Type Description'),
			  '#size' => 60,
			  '#maxlength' => 500,	
			'#default_value' => $field->assessment_description,			  
		);			
					  
		  
	 $form['buttons']['submit'] = array(                                                          
		'#type' => 'submit',
		'#value' => t('Edit Assessment Category'), 
                '#prefix' => '<br/><br/><br/><br/>',                                                
	  );
	  $form['edit']['buttons']['cancel'] = array(                                                          
		'#type' => 'submit',
		'#value' => t('Cancel'),                                                 
	  );

$form['edit']['buttons']['submit']['#attributes']['class']  = $form['edit']['buttons']['submit']['#attributes']['class'] . ' qbsubmit';

	return $form;
		


}

function assesstype_edit_submit ($form, &$form_state) {
 $op = $form_state['values']['op'];
 if ( $op == "Cancel" ) {
		  $form_state['redirect'] = 'assesstype/list';
		  return;	
	} 


		
	$assesstypeId = $form_state['values']['assessment_category_detail_id'];
	$userdefinedvalue = $form_state['values']['userdefinedvalue'];
	$userdefineddesc = $form_state['values']['userdefineddesc'];

	$userdefinedvalue = str_replace("'", "''", $userdefinedvalue);
	$userdefineddesc = str_replace("'", "''", $userdefineddesc);
			
		db_set_active('qtxt_db');
		
		db_query("update {cce_assesment_category_details} set  assessment_category_type = '%s', assessment_description = '%s' WHERE assessment_category_detail_id = %d ", $userdefinedvalue, $userdefineddesc, $assesstypeId);
			

		db_set_active('default');

		drupal_set_message(t('The Assessment Category  %field has been updated.', array('%field' => $form_state['values']['userdefinedvalue'])));

		cache_clear_all();
  		unset ( $_SESSION['group_filter_value'] );

		$form_state['redirect'] = 'assesstype/list';
		return;
}

function assesstype_delete(&$form_state, $fid) {


  
		db_set_active('qtxt_db');
		$field = db_fetch_object(db_query("SELECT assessment_category_type, assessment_name FROM {cce_assesment_category_details_v} WHERE assessment_category_detail_id = %d", $fid));
		db_set_active('default');

		if (!$field) {
			drupal_not_found();
			return;
		  }

		  $form['assesstypeid'] = array('#type' => 'value', '#value' => $fid);
		  $form['assesstypename'] = array('#type' => 'value', '#value' => $field->assessment_category_type);
		 // $form['groupdesc'] = array('#type' => 'value', '#value' => $field->group_description);

		  return confirm_form($form,
			t('Are you sure you want to delete the Assessment Category %field defined for Assessment Name %field2?', array('%field' => $field->assessment_category_type, '%field1' => $field->assessment_name)), 'assesstype',
			t('This action cannot be undone.  If you want to keep the user-entered data, instead of deleting the field you may wish to <a href="@edit-field">edit this field</a> .', array('@edit-field' => url('assesstype/edit/'. $fid))),
			t('Delete'), t('Cancel'));
		}

/**
 * Process a field delete form submission.
 */
function assesstype_delete_submit($form, &$form_state) {
		db_set_active('qtxt_db');
		db_query('DELETE FROM {cce_assesment_category_details} WHERE assessment_category_detail_id = %d', $form_state['values']['assesstypeid']);
		db_set_active('default');
		cache_clear_all();

		drupal_set_message(t('The Assessment Category  %field has been deleted.', array('%field' => $form_state['values']['assesstypename'])));
  		unset ( $_SESSION['group_filter_value'] );
		$form_state['redirect'] = 'assesstype/list';
		return;
}
function assesstype_delete_validate($form, &$form_state) {
$op = $form_state['values']['op'];
$ccode = $form_state['values']['assesstypeid'];
// drupal_set_message(t("Assessment id = $ccode"));
	db_set_active('qtxt_db');
		$field = db_fetch_object(db_query("SELECT assessment_category_detail_id FROM {cce_assesment_cat_det_descriptor} WHERE assessment_category_detail_id = $ccode"));	
		db_set_active('default');
		if ($field) {
				form_set_error('', t('You cant able to delete this Assessment Category, since Assessment Category Descriptors were already defined to the Assesment Descriptors'));
		}	
}


function cce_assesstype($callback_arg = '') {
/*
        $output = drupal_get_form('assesstype_filter_form');
        $output .= drupal_get_form('assesstype_details');
  return $output;
  */
  
  $op = isset($_POST['op']) ? $_POST['op'] : $callback_arg;

//  drupal_set_message("Operamd - $op ");	
  
  switch ($op) {
    case t('Create Assessment Category Type'):
    case 'create':
	case 'Cancel':
      $output = drupal_get_form('assesstype_create');
      break;

	  default:
      if (!empty($_POST['assesstype']) && isset($_POST['operation']) && ($_POST['operation'] == 'delete')) {
        $output = drupal_get_form('group_multiple_delete_confirm');
      }
      else {
        $output = drupal_get_form('assesstype_filter_form');
        $output .= drupal_get_form('assesstype_details');
      }
  }
  return $output;
  
}

function assesstype_create() {


db_set_active('qtxt_db');	
		$result1 = db_query("SELECT group_id, concat( group_name , ' - ' , group_description ) 'groupdesc' FROM {cce_groups} order by group_description ");
		$accessOptions = array( '' => t('Select the Group Name') );
		while ($row = db_fetch_object($result1)){
		  $accessOptions[$row->group_id ] = $row->groupdesc; 
		}
		db_set_active('default');	

		
		$form['group'] = array(
			'#type' => 'select',
			'#description' => t('Please select the Group Name'),
			'#options'=> $accessOptions,
			'#title' => t('Group'),
			'#disabled' => FALSE,
			'#ahah' => array(
				  	'path' => 'assesstype/group/ahahjs0',
				  	'wrapper' => 'ahah-wrapper-group',
				  	'method' => 'replace',
				  			)			
		);	


		db_set_active('qtxt_db');	
		$result1 = db_query("SELECT assessment_id, concat( group_name, ' - ' , assessment_name) assessment_name  FROM {cce_assesment_types_v} a order by group_name, assessment_id  ");
		$accessOptions = array( '' => t('Select the Assessment Name') );
		while ($row = db_fetch_object($result1)){
		  $accessOptions[$row->assessment_id ] = $row->assessment_name; 
		}
		db_set_active('default');	


		$form['assessname'] = array(
			'#type' => 'select',
			'#description' => t('Please select the Assessment Name'),
			'#options'=> $accessOptions,
			'#title' => t('Assessment Name'),
			'#disabled' => FALSE,
			'#ahah' => array(
				  	'path' => 'assesstype/year/ahahjs2',
				  	'wrapper' => 'ahah-wrapper-defaultlist',
				  	'method' => 'replace',
				  			),
'#prefix' => '<div id = "ahah-wrapper-group">',
				'#suffix' => '</div>',							
							
		);

		$form['default_list']=array(
				'#type'=>'select',
				'#title' => t('Default Assessment Category Type '),
				'#description' => t(' Values provided by CBSE. Plese use Ctls + Select to select multiple values.'),
				'#default_value' => array('1'=>'Joe'),
				'#options' =>  array( '' => t('Select ..') ),
				'#multiple' => true,
				'#attributes'=>array('size'=>20),
				 '#prefix' => '<div id = "ahah-wrapper-defaultlist">',
				'#suffix' => '</div>',
			);

		$form['userdefinedvalue'] = array(
			'#type' => 'textfield',
			'#description' => t('Please enter your own assessment category types'),
			'#title' => t('Other Assessment Category Type'),
			  '#size' => 60,
			  '#maxlength' => 500,	
		);			
			

		$form['userdefineddesc'] = array(
			'#type' => 'textfield',
			'#description' => t('Please enter assessment category type description'),
			'#title' => t('Assessment Category Type Description'),
			  '#size' => 60,
			  '#maxlength' => 500,	
		);	
		
			
			
	 $form['buttons']['submit'] = array(                                                          
		'#type' => 'submit',
		'#value' => t('Create Assessment Category Type'),
                '#prefix' => '<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>',                                                 
	  );
		
	 $form['edit']['buttons']['cancel'] = array(                                                          
		'#type' => 'submit',
		'#value' => t('Cancel'),                                                 
	  );

$form['buttons']['submit']['#attributes']['class']  = $form['buttons']['submit']['#attributes']['class'] . ' qbsubmit';


	return $form;

}

function assesstype_create_submit($form, &$form_state) {


		  
   $op = $form_state['values']['op'];
  
if ( $op == "Cancel" ) {
		  $form_state['redirect'] = 'assesstype/list';
		  return;	
	} 

	$assessId = $form_state['values']['assessname'];
	$default_list = $form_state['values']['default_list'];
	$groupname = $form_state['values']['section4'];
	$groupname = str_replace("'", "''", $groupname);		

	$userdefinedvalue = $form_state['values']['userdefinedvalue'];
	$userdefineddesc = $form_state['values']['userdefineddesc'];
	$userdefinedvalue = str_replace("'", "''", $userdefinedvalue);
	$userdefineddesc = str_replace("'", "''", $userdefineddesc);		

	$new_array = array_values($default_list); 		
	foreach($new_array as $key => $value) {
	  if($value == "") {
		unset($new_array[$key]);
	  }
	}

	$final_array = array_values($new_array); 	
	$finalcount= count(	$final_array );
	$comma_separated = implode(",", $final_array);
	
		db_set_active('qtxt_db');
		$field = db_fetch_object(db_query("select assessment_category_code, assessment_type_code from cce_assesment_types where assessment_id = %d", $assessId));
		db_set_active('default');

		if (!$field) {
			drupal_not_found();
			return;
		  }	
		$asscategcode = $field->assessment_category_code;
		$asstypecode = $field->assessment_type_code;

	//drupal_set_message(t("Your assesstypement Type - $comma_separated"));	
	//drupal_set_message("user defined - $userdefinedvalue ");	
	//drupal_set_message("user defined desc - $userdefineddesc ");	

	// drupal_set_message("Count - $groupname ");	

	if ( $finalcount > 0 ) {
		foreach ( $final_array as $k => $v) {
			db_set_active('qtxt_db');	
			$result1 = db_fetch_object( db_query("select assessment_category_type, assessment_description from cce_assesment_category_details_master where assessment_category_detail_id  = $v") );

			db_set_active('default');
			db_set_active('qtxt_db');
			global $user;
   $uid=$user->uid; 
                 $sql = "select account_id from {cce_account_admin} where drupal_uid=$uid "   ; 

   $resultg2 = db_query($sql);   
   while ($rowg2 = db_fetch_object($resultg2)) {
       $cceArray =  $rowg2->account_id ; 
   }
   db_set_active('default');
   $cceaccountid=$cceArray;
   drupal_set_message("hAI".$cceaccountid);		
			db_set_active('qtxt_db');	
		$result = db_query( "INSERT INTO `cce_assesment_category_details`   (`assessment_category_detail_id`,   `assessment_category_code`,   `assessment_category_type`,   `assessment_group`,   `assessment_description`,   `assessment_id`,   
		`assessment_type_code`,   `creation_date`,   `update_date`,   `created_by`,   `updated_by`, `master_assessment_category_detail_id`,`group_name`,`account_id`)  
		VALUES   (   null, '$asscategcode',    '$result1->assessment_category_type',  
		null,   '$result1->assessment_description',   $assessId,   '$asstypecode',  sysdate(),   sysdate(),   'admin',   'admin', $v,'$groupname' ,$cceaccountid )");  
		
			db_set_active('default');
//			drupal_set_message(t("Your Assessment Type has been inserted successfully."));			
			 
			}
	}			
	if ( $userdefinedvalue != "") {
	db_set_active('qtxt_db');
	global $user;
   $uid=$user->uid; 
                 $sql = "select account_id from {cce_account_admin} where drupal_uid=$uid "   ; 

   $resultg2 = db_query($sql);   
   while ($rowg2 = db_fetch_object($resultg2)) {
       $cceArray =  $rowg2->account_id ; 
   }
   db_set_active('default');
		db_set_active('qtxt_db');	
		$result = db_query( "INSERT INTO `cce_assesment_category_details`   (`assessment_category_detail_id`,   `assessment_category_code`,   `assessment_category_type`,   `assessment_group`,   `assessment_description`,   `assessment_id`,   `assessment_type_code`,   `creation_date`,   `update_date`,   `created_by`,   `updated_by`,`account_id`)   VALUES   (   null, '$asscategcode',   '$userdefinedvalue',   null,   '$userdefineddesc',   $assessId,   '$asstypecode',  sysdate(),   sysdate(),   'admin',   'admin' ,$cceArray  )");  

		db_set_active('default');			
	}

	drupal_set_message(t("Your Assessment Category Types have been inserted successfully."));	
	
	
/*

echo $comma_separated; 
		db_set_active('qtxt_db');

			$groupName = str_replace("'", "''", $groupName);
			$groupDesc = str_replace("'", "''", $groupDesc);
global $user;
   $uid=$user->uid; 
                 $sql = "select account_id from {cce_account_admin} where drupal_uid=$uid "   ; 

   $resultg2 = db_query($sql);   
   while ($rowg2 = db_fetch_object($resultg2)) {
       $cceArray =  $rowg2->account_id ; 
   }
   db_set_active('default');
db_set_active('qtxt_db');

			$result = db_query( "INSERT INTO `cce_assesment_types`  (`assesstypement_id`,  `term_id`,  `group_id`,  `assesstypement_category_code`,  `assesstypement_name`,  `period`,  `academic_weighting_percentage`,  `term_weighting_percentage`,  `grading_type_id`,  `ordering_sequence`,  `assesstypement_type_code`,  `creation_date`,  `update_date`,  `created_by`,  `updated_by`,`account_id`)  VALUES  (  null,  $terms,  $group,  '$category',  '$assesstypename',  '$period', $weightage,  $weightage, $grading,  $sequence,  '$assTypeCode',  sysdate(),  sysdate(),  'admin',  'admin',$cceArray  )");
		db_set_active('default');
			drupal_set_message(t("Your assesstypement Type has been inserted successfully."));	
*/
			unset ( $_SESSION['group_filter_value'] );
			unset ( $_SESSION['section_filter_value'] );
			unset ( $_SESSION['section1_filter_value'] );
			unset ( $_SESSION['section2_filter_value'] );
			
		  $form_state['redirect'] = 'assesstype/list';
		  return;

}



/**
 * Form builder; Return form for user administration filters.
 *
 * @ingroup forms
 * @see user_filter_form_submit()
 */
function assesstype_filter_form() {

			
	 $i = 0;
	  $form['filters'] = array(
		'#type' => 'fieldset',
		'#title' => t('Show only assesstype where'),

	  );
db_set_active('qtxt_db');	
		$result = db_query("select  distinct(group_name), group_id  from {cce_groups} order by group_name  " );
$sectionoptions2 = array('' => t('Select..'));

while ($row = db_fetch_object($result)) {
  $sectionoptions2[$row->group_id ] =  $row->group_name; //This is the only line that changed from the code above.
}
db_set_active('default');

$key = 'section2';				
 $names[$key] = 'Type ';

 $form['filters']['status'][$key] = array(
      '#type' => 'select',
	   '#title' => 'Group Name',
      '#options' => $sectionoptions2,
	  );

db_set_active('qtxt_db');	
		$result = db_query("select  distinct(term_name),term_id  from {cce_term} order by term_name  " );

$sectionoptions1 = array('' => t('Select..'));

while ($row = db_fetch_object($result)) {
  $sectionoptions1[$row->term_id ] =  $row->term_name; //This is the only line that changed from the code above.
}
db_set_active('default');

$key = 'section1';				
 $names[$key] = 'Type ';
 
 $form['filters']['status'][$key] = array(
      '#type' => 'select',
	  '#title' => 'Term Name ',
      '#options' => $sectionoptions1,
    );

db_set_active('qtxt_db');	
		$result = db_query("select  distinct(assessment_name), assessment_id  from {cce_assesment_category_details_v} order by assessment_name " );

$sectionoptions = array('' => t('Select..'));

while ($row = db_fetch_object($result)) {
  $sectionoptions[$row->assessment_name ] =  $row->assessment_name; //This is the only line that changed from the code above.
}
db_set_active('default');

$key = 'section';				
 $names[$key] = 'Type ';
 $form['filters']['status'][$key] = array(
      '#type' => 'select',
	  '#title' => 'Assessment Name ',
      '#options' => $sectionoptions,
    );
	


		db_set_active('qtxt_db');	

		$result = db_query("select assessment_category_type, assessment_description, assessment_category_code, assessment_category_detail_id  from {cce_assesment_category_details} order by assessment_category_type" );

		$options = array('' => t('Select..'));

		$c2Val = "";
		$c3Val = "";
		$c4Val = "";
		$c5Val = "";		
		
		if(!empty($_SESSION['group_filter_value'])) {
			$c2Val = &$_SESSION['group_filter_value'];
		} else {
			$c2Val = "";
		}
		if(!empty($_SESSION['section_filter_value'])) {
			$c3Val = &$_SESSION['section_filter_value'];
		} else {
			$c3Val = "";
		}
		if(!empty($_SESSION['section1_filter_value'])) {
			$c4Val = &$_SESSION['section1_filter_value'];
		} else {
			$c4Val = "";
		}
		if(!empty($_SESSION['section2_filter_value'])) {
			$c5Val = &$_SESSION['section2_filter_value'];
		} else {
			$c5Val = "";
		}
		
		
		while ($row = db_fetch_object($result)) {
				$options[$row->assessment_category_detail_id ] =  $row->assessment_category_type; 
		}

		db_set_active('default');	 
		

		$form['filters']['group'] = array(
		  '#title' => 'Assessment Category Type like ',
		  '#type' => 'textfield',
		  '#size' => 60,
		  '#maxlength' => 128,
		  '#default_value' => $c2Val,

		);
		
		
	
	


	 $form['filters']['buttons']['submit'] = array(                                                          
		'#type' => 'submit',
		'#value' => t('Filter'),  
                '#prefix' => '<br/>',                                               
	  );

$form['filters']['buttons']['submit']['#attributes']['class']  = $form['filters']['buttons']['submit']['#attributes']['class'] . ' qbsubmit';

	return $form;

}



function assesstype_filter_form_submit($form, &$form_state) {
  $op = $form_state['values']['op'];
//  drupal_set_message("Filter Form Submit Operamd - $op ");	  
  switch ($op) {
    case t('Filter'): 


      if (isset($form_state['values']['group'])) {
			// drupal_set_message(t("In the Filter, Class  selected"));	 	  
			$filter = $form_state['values']['group'];
			// drupal_set_message(t("In the Filter, $filter"));	 	  
			
			$_SESSION['group_filter_value'] = $form_state['values']['group'];
	  }
	   if (isset($form_state['values']['section'])) {
			// drupal_set_message(t("In the Filter, Class  selected"));	 	  
			$filter = $form_state['values']['section'];
			// drupal_set_message(t("In the Filter, Class  $filter"));	 	  
			
			$_SESSION['section_filter_value'] = $form_state['values']['section'];
	  }
	   if (isset($form_state['values']['section1'])) {
			// drupal_set_message(t("In the Filter, Class  selected"));	 	  
			$filter = $form_state['values']['section1'];
			// drupal_set_message(t("In the Filter, Class  selected $filter"));	 	  
			
			$_SESSION['section1_filter_value'] = $form_state['values']['section1'];
	  }
	   if (isset($form_state['values']['section2'])) {
			// drupal_set_message(t("In the Filter, Class  selected"));	 	  
			$filter = $form_state['values']['section2'];
			// drupal_set_message(t("In the Filter, Class  selected - $filter"));	 	  
			
			$_SESSION['section2_filter_value'] = $form_state['values']['section2'];
	  }
	 
	 
	 
	  
      break;
  }
  
  $form_state['redirect'] = 'assesstype';
  return;
}



function assesstype_details($form_state) {
global $user;
$profile =  profile_load_profile($user);
$myMobileNumber =  $user->profile_mobile;  

  $header = array(
    array(),
    array('data' => t('Group Name'), 'field' => 'b.standard'),
    array('data' => t('Group Description'), 'field' => 'b.section'),
	t('Operations'),
  );

$clVal = &$_SESSION['group_filter_value'] ;
// drupal_set_message(t("Class Filter 1 - $clVal"));
$c2Val = &$_SESSION['section_filter_value'] ;
// drupal_set_message(t("Class Filter 1 - $c2Val"));	
$c3Val = &$_SESSION['section1_filter_value'] ;
// drupal_set_message(t("Class Filter 1 - $c3Val"));	
$c4Val = &$_SESSION['section2_filter_value'] ;
// drupal_set_message(t("Class Filter 1 - $c4Val"));	
	

  
$filterClass = "";
    if ( $clVal != "" ) {
		$clVal = strtoupper($clVal);
			$filterClass = " and upper(b.assessment_category_type) like '%$clVal%' ";
			// drupal_set_message(t("Class1 - $filterClass"));
	} else {
			$filterClass = " and b.assessment_category_type = b.assessment_category_type ";
	}
$filterClass1 = "";
	if ( $c2Val != "" ) {
					$filterClass1 = " and b.assessment_name  = '$c2Val' ";
					// drupal_set_message(t("Class1 - $filterClass1"));
	} else {
			$filterClass1 = " and  b.assessment_name = b.assessment_name ";
	}
	$filterClass2 = "";
	if ( $c3Val != "" ) {
		
			$filterClass2 = " and b.term_id = $c3Val ";
			// drupal_set_message(t("Class1 - $filterClass2"));
	} else {
			$filterClass2 = " and b.term_id = b.term_id ";
	}
	$filterClass3 = "";
	if ( $c4Val != "" ) {
			$filterClass3 = " and b.group_id= $c4Val ";
			// drupal_set_message(t("Class1 - $filterClass3"));
	} else {
			$filterClass3 = " and b.group_id = b.group_id ";
	}
	


  db_set_active('qtxt_db');	
  $sql = "select assessment_category_type, assessment_description, assessment_name , assessment_category_desc, group_name, term_name, year,
 assessment_type_code , assessment_category_detail_id, assessment_id  from  {cce_assesment_category_details_v} b  where 1 = 1  " 
. $filterClass  . $filterClass1  . $filterClass2  . $filterClass3  ." order by assessment_name, assessment_category_type " ; 


    $query_count = "select COUNT(assessment_category_detail_id) from  {cce_assesment_category_details_v} b  where 1 = 1 " 
. $filterClass  . $filterClass1  . $filterClass2  . $filterClass3   ;


  
   $sql .= tablesort_sql($header);

  $result = pager_query($sql, 1000, 0, $query_count);
  db_set_active('default');


    $form['access'] = array(
    '#type' => 'fieldset',
    '#title' => t('Access log settings'),
    '#tree' => TRUE,
	'#visible' => false,
  );


  $accounts = array();

$i = 1;  
  while ($account = db_fetch_object($result)) {

  $form['access']['account'][$i] = array(
		'#type' => 'checkbox',
		'#return_value' => $account->assessment_category_detail_id,
		'#default_value' => 0,
		'#tree' => TRUE,

	  );

 
 
    $form['access']['assessment_category_type'][$account->assessment_category_detail_id] = array('#value' => $account->assessment_category_type);
    $form['access']['assessment_description'][$account->assessment_category_detail_id] =  array('#value' => $account->assessment_description);
    $form['access']['assessment_name'][$account->assessment_category_detail_id] = array('#value' => $account->assessment_name);
    $form['access']['assessment_category_desc'][$account->assessment_category_detail_id] =  array('#value' => $account->assessment_category_desc);
    $form['access']['group_name'][$account->assessment_category_detail_id] = array('#value' => $account->group_name);
    $form['access']['term_name'][$account->assessment_category_detail_id] =  array('#value' => $account->term_name);
    $form['access']['year'][$account->assessment_category_detail_id] = array('#value' => $account->year);
    $form['access']['assessment_type_code'][$account->assessment_category_detail_id] =  array('#value' => $account->assessment_type_code);
    
	
 //   $form['access']['assessment_id'][$account->assessment_category_detail_id] =  array('#value' => $account->assessment_id);
	
    $form['access']['assessment_category_detail_id'][$account->assessment_category_detail_id] =  array('#type'=> hidden,'#value' => $account->assessment_category_detail_id);
	$form['access']['operations'][$account->assessment_category_detail_id] = array('#value' => l(t('edit'), "assesstype/edit/$account->assessment_category_detail_id", array('query' => $destination)));	
	$form['access']['operations2'][$account->assessment_category_detail_id] = array('#value' => l(t('delete'), "assesstype/delete/$account->assessment_category_detail_id", array('query' => $destination)));	
	$i = $i + 1;
  }
// db_set_active('default');

  $form['pager'] = array('#value' => theme('pager', NULL, 1000, 0));
  $form['#theme'] = 'access_type_description_theme';   
  $form['totalcount'] = array(
	'#type' => 'hidden', '#default_value' => ($i  -1 )
  );  
  return $form;
}

function v3_cce_assesstype_theme() {
	return array(
		'access_type_description_theme' => array('arguments'=> array('form' => NULL),),
	);
}

function theme_access_type_description_theme($form)
{
$rows = array();
$i = 1;

foreach(element_children($form['access']['assessment_category_detail_id']) as $key) {
	$row = array(); 
//       $row[] =  drupal_render($form['access']['account'][$i]);
 $row[] =  drupal_render($form['access']['year'][$key]);
 $row[] =  drupal_render($form['access']['term_name'][$key]);
 $row[] =  drupal_render($form['access']['group_name'][$key]);
 $row[] =  drupal_render($form['access']['assessment_name'][$key]);
  $row[] =  drupal_render($form['access']['assessment_description'][$key]);
   $row[] =  drupal_render($form['access']['assessment_category_type'][$key]);         
   $row[] =  drupal_render($form['access']['assessment_category_desc'][$key]);
      
      
       $row[] =  drupal_render($form['access']['assessment_type_code'][$key]);
      //  $row[] =  drupal_render($form['access']['assessment_id'][$key]);
      //  $row[] =  drupal_render($form['access']['assessment_category_detail_id'][$key]);
       $row[] =  drupal_render($form['access']['operations'][$key]);	   
       $row[] =  drupal_render($form['access']['operations2'][$key]);	   
	$rows[] = $row; 
	$i = $i +1 ;
}

if(count($rows)){
//			$header = array( theme('table_select_header_cell'), t('Group Name'), t('Group Desc'), t('Group Id') );
				$header = array( t('Year'), t('Term Name'),t('Group Name'),  t('Assessment Name'), t('Assessment Description'), t('Assessment Category Type'), t('Assessment Category Description'),  t('Assessment Type Code'));
				
				  $header[] = array('data' => t('Operations'), 'colspan' => 2);
  }
  else{
    $header = array(t('Assessment Category Type'), t('Year')); 
    $row = array();
    $row[] = array
    (
      'data' => t('No assesstype were found'),
      'colspan' => 2,
      'style' => 'text-align:center'
    );
    $rows[] = $row;
  }
$output = theme('table', $header, $rows); 
//$output .= drupal_render($form['options']); 
// $output .= drupal_render($form['options']['submit']); 
  $form['access']['#access'] = false;
 return $output . drupal_render($form); 
 return $output ; 
}  





function ahah_for_assterm_to_derive_defaultvalues() {

$form_state = array('storage' => NULL, 'submitted' => FALSE);
		$form_build_id = $_POST['form_build_id'];

		// Get for the form from the cache
		$form = form_get_cache($form_build_id, $form_state);
  
		// Get the form set up to process
		$args = $form['#parameters'];
		$form_id = array_shift($args);
		$form_state['post'] = $form['#post'] = $_POST;
		$gid = $form['#post']['assessname'];
		db_set_active('qtxt_db');

		$sqlg = "select  b.assessment_category_type, b.assessment_category_detail_id     from cce_assesment_types a, cce_assesment_category_details_master b  
where assessment_id = $gid  and b.assessment_category_code = a.assessment_category_code  and not exists
 ( select '*' from cce_assesment_category_details x where x.assessment_id = a.assessment_id  and upper(x.assessment_category_type) = upper(b.assessment_category_type ) ) ";

        $resultg = db_query($sqlg);
		$valueg[''] = 'Select a Value.. ';
		while($datag = db_fetch_object($resultg))
		{
		$valueg[$datag->assessment_category_detail_id] = $datag->assessment_category_type;
		}
		db_set_active('default');
		$result = count($valueg);
		if ( $result == 1 )  {
			$valueg[''] = 'All default values have been defined..';
		}

		$form['default_list']['#options'] = $valueg;
		$form['default_list']['#multiple'] = true;
		$form['default_list']['#attributes'] = array('size'=>20);
		
		form_set_cache($form_build_id, $form, $form_state);
				$form += array(
					'#post' => $_POST,
					'#programmed' => FALSE,
				  );
	
           $form = form_builder('form_details', $form, $form_state);			
				$output = $form['default_list'];
				unset($output['#prefix'],$output['#suffix']);
				$out1 =  drupal_render($output);
				drupal_json(array('status' => TRUE, 'data' => $out1));

}

function assesstype_ahah_for_group() {

$form_state = array('storage' => NULL, 'submitted' => FALSE);
		$form_build_id = $_POST['form_build_id'];

		// Get for the form from the cache
		$form = form_get_cache($form_build_id, $form_state);
  
		// Get the form set up to process
		$args = $form['#parameters'];
		$form_id = array_shift($args);
		$form_state['post'] = $form['#post'] = $_POST;
		$gid = $form['#post']['group'];
		db_set_active('qtxt_db');

//		$sqlg = "select  b.assessment_id, b.assessment_name  from cce_assesment_types b  where group_id = $gid and assessment_category_code  in ( 'FA', 'SA')";
		$sqlg = "select  b.assessment_id, b.assessment_name  from cce_assesment_types b  where group_id = $gid order by assessment_name ";

 // $sqlg = "SELECT assessment_id, concat( group_name, ' - ' , assessment_name) assessment_name  FROM {cce_assesment_types_v} a order by group_name, assessment_id   ";

        $resultg = db_query($sqlg);
		$valueg[''] = 'Select a Value.. ';
		while($datag = db_fetch_object($resultg))
		{
		$valueg[$datag->assessment_id] = $datag->assessment_name;
		}
		db_set_active('default');
		
		$form['assessname']['#options'] = $valueg;
		
		$form['assessname']['#ahah'] = array(
				  	'path' => 'assesstype/year/ahahjs2',
				  	'wrapper' => 'ahah-wrapper-defaultlist',
				  	'method' => 'replace',
				  			)	;
		$form['assessname']['#prefix'] = '<div id = "ahah-wrapper-group">';
		$form['assessname']['#suffix'] =  '</div>';		
							
		form_set_cache($form_build_id, $form, $form_state);
				$form += array(
					'#post' => $_POST,
					'#programmed' => FALSE,
				  );
	
           $form = form_builder('form_details', $form, $form_state);			
				$output = $form['assessname'];
				unset($output['#prefix'],$output['#suffix']);
				$out1 =  drupal_render($output);
				drupal_json(array('status' => TRUE, 'data' => $out1));

}